// AUTO-GENERATED from /upload/Pasted Content_1789230174908.txt
// Source: user-supplied show catalog (68 shows).
import { Movie, Playlist, MovieCategory } from "./types";

// Sample YouTube video IDs cycled across episodes for each show.
// In production, replace these with the real per-episode YouTube IDs
// fetched from each show's YouTube playlist (`playlist_id` field).
const SAMPLE_YT_IDS = [
  "aqz-KE-bpKQ",
  "eRsGyueVLvQ",
  "R6MlUcmOul8",
  "TLkA0RELQ1g",
  "WhWc3b3KhnY",
  "LXb3EKWsInQ",
  "fNqkXKKWBgs",
  "M7lc1UVf-VE",
  "MgIdv3iYYOw",
  "YbJOTdToBXs",
];

// Build a placeholder episode list for each show. We don't have real
// per-episode YouTube IDs, so we cycle SAMPLE_YT_IDS for each episode.
function makeEpisodes(prefix: string, showName: string, count: number, thumb: string) {
  const result: import("./types").Episode[] = [];
  for (let i = 0; i < count; i++) {
    const num = i + 1;
    result.push({
      id: `${prefix}-ep-${num}`,
      episodeNumber: num,
      seasonNumber: 1,
      title: `${showName} — Episode ${num}`,
      description: `Episode ${num} of ${showName}.`,
      duration: `${20 + (num % 15)}m`,
      thumbnail: thumb,
      youtubeId: SAMPLE_YT_IDS[i % SAMPLE_YT_IDS.length],
      airDate: `2024-${String((i % 12) + 1).padStart(2, "0")}-15`,
    });
  }
  return result;
}

export const SHOW_MOVIES: Movie[] = [
  {
    id: `gumball`,
    title: `The Amazing World of Gumball`,
    poster: `https://m.media-amazon.com/images/M/MV5BNmEwYzNhODgtZDc2Yi00MDAyLTliNWYtMDRkMThmMWE0NGNkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BNmEwYzNhODgtZDc2Yi00MDAyLTliNWYtMDRkMThmMWE0NGNkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`,
    year: 2011,
    rating: `TV-PG`,
    duration: `6 Seasons • 240 Eps`,
    genres: ["Komedi","Macera"],
    description: `Gumball Watterson ve ailesiyle Elmore şehrindeki çılgın gündelik maceralar.`,
    playlistId: `pl-gumball`,
    youtubePlaylistId: `PLC8MXDuDxrrsyqbTa9nK_gq8qmiMfR3sM`,
    featured: true,
  },
  {
    id: `theloudhouse`,
    title: `The Loud House`,
    poster: `https://m.media-amazon.com/images/M/MV5BZjlkMmQ5YzItZGRmMy00NjVjLWIwYmMtMzJjM2QxM2Q1OThkXkEyXkFqcGc@._V1_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BZjlkMmQ5YzItZGRmMy00NjVjLWIwYmMtMzJjM2QxM2Q1OThkXkEyXkFqcGc@._V1_.jpg`,
    year: 2016,
    rating: `TV-PG`,
    duration: `7 Seasons • 130 Eps`,
    genres: ["Komedi","Macera"],
    description: `10 kardeşin ortası Lincoln Loud, kaotik ev hayatında hayatta kalmaya çalışır.`,
    playlistId: `pl-theloudhouse`,
    youtubePlaylistId: `PLgrisE0MOLgRBNWk2cbO035kQ0hHA11HC`,
  },
  {
    id: `ben10ultimatealien`,
    title: `Ben 10 Alien Force`,
    poster: `https://m.media-amazon.com/images/M/MV5BOGQ5YWFjYjItODE5OC00ZDQxLTk5ZmYtNzY0YzM4NjIyMWFlXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BOGQ5YWFjYjItODE5OC00ZDQxLTk5ZmYtNzY0YzM4NjIyMWFlXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`,
    year: 2008,
    rating: `TV-Y7-FV`,
    duration: `3 Seasons • 46 Eps`,
    genres: ["Aksiyon","Macera"],
    description: `Ben Tennyson 15 yaşında uzaylı tehditlerle tekrar savaşa giriyor.`,
    playlistId: `pl-ben10ultimatealien`,
    youtubePlaylistId: `PLD7E4B63582E0479D`,
  },
  {
    id: `beastboy`,
    title: `Beast Boy Lone Wolf`,
    poster: `https://m.media-amazon.com/images/M/MV5BYzQxY2FjOWItNjc0Mi00NGNjLTg5NGYtNDBhNzdjMDBmN2Q4XkEyXkFqcGc@._V1_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BYzQxY2FjOWItNjc0Mi00NGNjLTg5NGYtNDBhNzdjMDBmN2Q4XkEyXkFqcGc@._V1_.jpg`,
    year: 2023,
    rating: `TV-Y7-FV`,
    duration: `1 Season • 38 Eps`,
    genres: ["Aksiyon","Macera"],
    description: `Yeni nesil Beyblade turnuvaları ve efsanevi X dönüşümü.`,
    playlistId: `pl-beastboy`,
    youtubePlaylistId: `PLTJkpTzCerNrGfBN3Li4vR3Uegu1-TglA`,
  },
  {
    id: `SpongeBobSquarePants`,
    title: `SpongeBob SquarePants Haloween`,
    poster: `https://m.media-amazon.com/images/M/MV5BYjJmMjBkZjMtZThiZS00Nzk3LWJlN2UtYmE5ZjkyNjJiZjgxXkEyXkFqcGc@._V1_QL75_UY281_CR1,0,190,281_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BYjJmMjBkZjMtZThiZS00Nzk3LWJlN2UtYmE5ZjkyNjJiZjgxXkEyXkFqcGc@._V1_QL75_UY281_CR1,0,190,281_.jpg`,
    year: 1999,
    rating: `TV-PG`,
    duration: `14 Seasons • 280 Eps`,
    genres: ["Komedi","Macera"],
    description: `Bikini Bottom'da yaşayan süngerin çılgın sualtı maceraları.`,
    playlistId: `pl-SpongeBobSquarePants`,
    youtubePlaylistId: `PLShpyCq1QZaynW4FN2Nbf-XnlPz0RNV7L`,
  },
  {
    id: `RegularShowLostTapes`,
    title: `Regular Show lost Tapes`,
    poster: `https://m.media-amazon.com/images/M/MV5BNDY5ZTA4ZGQtMzE2Ni00YjQ1LTk4ODktZGQwYTgwYWYxNjUwXkEyXkFqcGc@._V1_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BNDY5ZTA4ZGQtMzE2Ni00YjQ1LTk4ODktZGQwYTgwYWYxNjUwXkEyXkFqcGc@._V1_.jpg`,
    year: 2010,
    rating: `TV-PG`,
    duration: `8 Seasons • 261 Eps`,
    genres: ["Komedi","Macera"],
    description: `Mordecai ve Rigby'nin sıradan bir parkta yaşadığı olağandışı olaylar.`,
    playlistId: `pl-RegularShowLostTapes`,
    youtubePlaylistId: `PLTQesLu3nTxsDo01ZXTZhx4Gv3WcFjvcS`,
  },
  {
    id: `AdventureTime`,
    title: `Adventure Time`,
    poster: `https://occ-0-753-1007.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABRV_sMrvu3tWVViD3FG-maRs7pdM01pKVjISgK7zVIeTEQTF0E0gX2VGS-crJoN5YxzYRZIZrKfCG2W26ZRo34i3acw6fdOzwkFr6YJbYufEGQM0v8be2W-M8da2L9HC.jpg?r=7fb`,
    backdrop: `https://occ-0-753-1007.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABRV_sMrvu3tWVViD3FG-maRs7pdM01pKVjISgK7zVIeTEQTF0E0gX2VGS-crJoN5YxzYRZIZrKfCG2W26ZRo34i3acw6fdOzwkFr6YJbYufEGQM0v8be2W-M8da2L9HC.jpg?r=7fb`,
    year: 2010,
    rating: `TV-PG`,
    duration: `10 Seasons • 283 Eps`,
    genres: ["Macera","Fantezi"],
    description: `Finn ve Jake'in Ooo Diyarı'ndaki epik maceraları.`,
    playlistId: `pl-AdventureTime`,
    youtubePlaylistId: `PLLIU9nFd9IrEsR2bcrJEGERa_91aYntWX`,
  },
  {
    id: `MutantNinjaTurtles`,
    title: `Teenage Mutant Ninja Turtles`,
    poster: `https://m.media-amazon.com/images/M/MV5BZTA0ZTlkMGItNTJmYy00YTVkLTgwMDktZTJiNTE5NmQ0ZWI4XkEyXkFqcGc@._V1_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BZTA0ZTlkMGItNTJmYy00YTVkLTgwMDktZTJiNTE5NmQ0ZWI4XkEyXkFqcGc@._V1_.jpg`,
    year: 2012,
    rating: `TV-Y7-FV`,
    duration: `5 Seasons • 124 Eps`,
    genres: ["Aksiyon","Macera"],
    description: `Dört kaplumbağa ninja New York'u korumak için gece karanlığına çıkıyor.`,
    playlistId: `pl-MutantNinjaTurtles`,
    youtubePlaylistId: `PL9FtL6eB-Npz_3om-MWlUXWQ87eWzaxl9`,
  },
  {
    id: `TransformersEarthSpark`,
    title: `Transformers EarthSpark`,
    poster: `https://m.media-amazon.com/images/M/MV5BNjAxNmRhZjctYTk1Ni00MGJjLThkY2YtNjdmODJjYTMwOGJlXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BNjAxNmRhZjctYTk1Ni00MGJjLThkY2YtNjdmODJjYTMwOGJlXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`,
    year: 2022,
    rating: `TV-Y7-FV`,
    duration: `2 Seasons • 26 Eps`,
    genres: ["Aksiyon","Sci-Fi"],
    description: `Dünyada doğan ilk Terran Transformers ile insanlığın yeni bir birlikteliği.`,
    playlistId: `pl-TransformersEarthSpark`,
    youtubePlaylistId: `PL7VEq3tXc6hsvHKfzdknf8GViPEr5JW5W`,
  },
  {
    id: `Ninjago`,
    title: `Ninjago`,
    poster: `https://ninjagoizlesene.com.tr/wp-content/uploads/2026/03/Crystalized-Poster-scaled.jpg`,
    backdrop: `https://ninjagoizlesene.com.tr/wp-content/uploads/2026/03/Crystalized-Poster-scaled.jpg`,
    year: 2011,
    rating: `TV-Y7-FV`,
    duration: `15 Seasons • 200 Eps`,
    genres: ["Aksiyon","Macera"],
    description: `Spinjitzu ustası Garmadon'a karşı savaşan dört ninjanın destanı.`,
    playlistId: `pl-Ninjago`,
    youtubePlaylistId: `PLwf-K0eNy8ANtvsRvluuNfPIEd3db5r8k`,
  },
  {
    id: `gravityfalls`,
    title: `Gravity Falls`,
    poster: `https://m.media-amazon.com/images/I/917WCiqRo6L._AC_UF1000,1000_QL80_.jpg`,
    backdrop: `https://m.media-amazon.com/images/I/917WCiqRo6L._AC_UF1000,1000_QL80_.jpg`,
    year: 2012,
    rating: `TV-PG`,
    duration: `2 Seasons • 40 Eps`,
    genres: ["Gizem","Komedi"],
    description: `Dipper ve Mabel'in büyükannesinin yanında geçirdikleri paranormal yaz tatili.`,
    playlistId: `pl-gravityfalls`,
    youtubePlaylistId: `PL5VwaAJ3JDSHr9ZnkEgu8GLC_x1JxrPcc`,
  },
  {
    id: `stevenuniverse`,
    title: `Steven Universe`,
    poster: `https://m.media-amazon.com/images/M/MV5BZGJjMmI3ZDMtZTgyNi00MTZhLWE2ZjAtN2Q4YTUyMTg4OGY1XkEyXkFqcGc@._V1_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BZGJjMmI3ZDMtZTgyNi00MTZhLWE2ZjAtN2Q4YTUyMTg4OGY1XkEyXkFqcGc@._V1_.jpg`,
    year: 2013,
    rating: `TV-PG`,
    duration: `5 Seasons • 160 Eps`,
    genres: ["Macera","Müzikal"],
    description: `Yarı insan yarı Kristal Mücevher olan Steven'ın dünyayı kurtarma yolculuğu.`,
    playlistId: `pl-stevenuniverse`,
    youtubePlaylistId: `PLIw4JuB69kRqSaga1p7kzPx99UOgrvRMA`,
  },
  {
    id: `FairlyOdd`,
    title: `The Fairly OddParents`,
    poster: `https://m.media-amazon.com/images/M/MV5BY2RlNWMwZmUtMjM4MC00MDczLTk3NjktYTg2OTNiNThhNmNhXkEyXkFqcGc@._V1_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BY2RlNWMwZmUtMjM4MC00MDczLTk3NjktYTg2OTNiNThhNmNhXkEyXkFqcGc@._V1_.jpg`,
    year: 2001,
    rating: `TV-PG`,
    duration: `10 Seasons • 172 Eps`,
    genres: ["Komedi","Fantezi"],
    description: `Timmy Turner'ın peri vaftiz anne babaları ile yaptığı dilekler hep çığırından çıkıyor.`,
    playlistId: `pl-FairlyOdd`,
    youtubePlaylistId: `PLZb1SVCX0ajoclQynrUz26jQm3aJ7Y0uS`,
  },
  {
    id: `clarence`,
    title: `Clarence`,
    poster: `https://m.media-amazon.com/images/M/MV5BMjNhYWQ3ZjgtYWQ2Ny00MzQ4LWFiODgtMWJkZDYwYWE1NDZmXkEyXkFqcGc@._V1_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BMjNhYWQ3ZjgtYWQ2Ny00MzQ4LWFiODgtMWJkZDYwYWE1NDZmXkEyXkFqcGc@._V1_.jpg`,
    year: 2014,
    rating: `TV-PG`,
    duration: `3 Seasons • 121 Eps`,
    genres: ["Komedi","Macera"],
    description: `Aşırı iyimser çocuk Clarence'ın sıradan gündelik hayatın tadını çıkaran maceraları.`,
    playlistId: `pl-clarence`,
    youtubePlaylistId: `PLg6KfZlgBuDVJM8_fYqLiBivHRmsu_lOj`,
  },
  {
    id: `mira`,
    title: `Miraculous Ladybug`,
    poster: `https://image.tmdb.org/t/p/w500/mwAJcSPtuRddU8AeL9lup5jE0Bn.jpg`,
    backdrop: `https://image.tmdb.org/t/p/w500/mwAJcSPtuRddU8AeL9lup5jE0Bn.jpg`,
    year: 2015,
    rating: `TV-PG`,
    duration: `5 Seasons • 130 Eps`,
    genres: ["Macera","Romantik"],
    description: `Paris'i koruyan iki genç kahraman — Ladybug ve Cat Noir.`,
    playlistId: `pl-mira`,
    youtubePlaylistId: `PLaMHyq8hhBW1o-vm10TyFjxtjNG2po9ze`,
  },
  {
    id: `codename`,
    title: `Codename: Kids Next Door Shorts`,
    poster: `https://www.tvtime.com/_next/image?url=https%3A%2F%2Fartworks.thetvdb.com%2Fbanners%2Fposters%2F71685-2.jpg&w=640&q=75`,
    backdrop: `https://www.tvtime.com/_next/image?url=https%3A%2F%2Fartworks.thetvdb.com%2Fbanners%2Fposters%2F71685-2.jpg&w=640&q=75`,
    year: 2002,
    rating: `TV-PG`,
    duration: `6 Seasons • 78 Eps`,
    genres: ["Komedi","Macera"],
    description: `Beş çocuktan oluşan gizli ajan ekibi yetişkinlere karşı savaşıyor.`,
    playlistId: `pl-codename`,
    youtubePlaylistId: `PL258poKABt5XHZ4aHMIRme6M9ichpplwg`,
  },
  {
    id: `circus`,
    title: `The Amazing Digital Circus`,
    poster: `https://fr.web.img5.acsta.net/c_310_420/img/e0/d1/e0d113764c9c629f20a681041ab4e01c.jpg`,
    backdrop: `https://fr.web.img5.acsta.net/c_310_420/img/e0/d1/e0d113764c9c629f20a681041ab4e01c.jpg`,
    year: 2023,
    rating: `TV-PG`,
    duration: `1 Season • 6 Eps`,
    genres: ["Komedi","Gizem"],
    description: `Dijital bir sirkde mahsur kalan insanların var olmaya çalışması.`,
    playlistId: `pl-circus`,
    youtubePlaylistId: `PLHovnlOusNLgvAbnxluXCVB3KLj8e4QB-`,
  },
  {
    id: `sonicprime`,
    title: `Sonic Prime`,
    poster: `https://preview.redd.it/what-makes-sonic-prime-forgettable-than-the-other-sonic-v0-vka3qbs2w7ye1.png?width=640&crop=smart&auto=webp&s=3dd7cbb9b2bacdd621b34b37d25904ca536ab061`,
    backdrop: `https://preview.redd.it/what-makes-sonic-prime-forgettable-than-the-other-sonic-v0-vka3qbs2w7ye1.png?width=640&crop=smart&auto=webp&s=3dd7cbb9b2bacdd621b34b37d25904ca536ab061`,
    year: 2022,
    rating: `TV-Y7-FV`,
    duration: `3 Seasons • 24 Eps`,
    genres: ["Aksiyon","Macera"],
    description: `Sonic çoklu evrende yolculuk ederek arkadaşlarını ve Shatterverse'ü kurtarıyor.`,
    playlistId: `pl-sonicprime`,
    youtubePlaylistId: `PLl5oejYNsf65FB-cWNS2JKsXWyEobLszM`,
  },
  {
    id: `ttg`,
    title: `Teen Titans Go!`,
    poster: `https://m.media-amazon.com/images/M/MV5BMjE5MjMzOTc1Ml5BMl5BanBnXkFtZTcwNDQxMDY5OQ@@._V1_FMjpg_UX1000_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BMjE5MjMzOTc1Ml5BMl5BanBnXkFtZTcwNDQxMDY5OQ@@._V1_FMjpg_UX1000_.jpg`,
    year: 2013,
    rating: `TV-Y7-FV`,
    duration: `8 Seasons • 350 Eps`,
    genres: ["Komedi","Aksiyon"],
    description: `Teen Titans'ın gündelik kahramanlık dışı komik maceralarını anlatan spin-off.`,
    playlistId: `pl-ttg`,
    youtubePlaylistId: `PLd3-CCCcbQeKcs5A_b8x45cTjZ0TFk-yn`,
  },
  {
    id: `kiff`,
    title: `Kiff`,
    poster: `https://m.media-amazon.com/images/M/MV5BMjA1NjIwNTMtY2Q2Ny00ZmVjLThkODItODg1ZjJmN2FjMDUzXkEyXkFqcGc@._V1_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BMjA1NjIwNTMtY2Q2Ny00ZmVjLThkODItODg1ZjJmN2FjMDUzXkEyXkFqcGc@._V1_.jpg`,
    year: 2020,
    rating: `TV-PG`,
    duration: `2 Seasons • 20 Eps`,
    genres: ["Komedi"],
    description: `Bir ortaokul öğrencisinin maceraları.`,
    playlistId: `pl-kiff`,
    youtubePlaylistId: `PLCGQDmE5nVHriQOifbcVibE_gKshXJIhd`,
  },
  {
    id: `tomandjerry`,
    title: `Tom and Jerry`,
    poster: `https://m.media-amazon.com/images/M/MV5BODY2YWI1OTAtY2FhZS00MGI1LTk0YjUtYmE3MDk0OGFkMWUyXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BODY2YWI1OTAtY2FhZS00MGI1LTk0YjUtYmE3MDk0OGFkMWUyXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`,
    year: 1940,
    rating: `TV-PG`,
    duration: `1 Season • 161 Eps`,
    genres: ["Komedi"],
    description: `Kedi Tom ve fare Jerry arasındaki hiç bitmeyen kovalamaca.`,
    playlistId: `pl-tomandjerry`,
    youtubePlaylistId: `PLeWt4i89tkloEBo3eyC_ZKKNrwL277eG_`,
  },
  {
    id: `batmanunlimited`,
    title: `Batman Unlimited`,
    poster: `https://play-lh.googleusercontent.com/RWN0fec0a0lc8Y-VBfDHcnN-L3OrwE-xcu3SN0dQ8UWrdpn_B-LI0OxnHOKXZysB5hPZ`,
    backdrop: `https://play-lh.googleusercontent.com/RWN0fec0a0lc8Y-VBfDHcnN-L3OrwE-xcu3SN0dQ8UWrdpn_B-LI0OxnHOKXZysB5hPZ`,
    year: 2010,
    rating: `TV-Y7-FV`,
    duration: `1 Season • 10 Eps`,
    genres: ["Aksiyon","Animasyon"],
    description: `Batman'ın ve diğer super kahramanların maceraları.`,
    playlistId: `pl-batmanunlimited`,
    youtubePlaylistId: `PLLDIqfKdBJnOcW48eRV9A0sweGS-Ex8NM`,
  },
  {
    id: `thundermans`,
    title: `The Thundermans`,
    poster: `https://m.media-amazon.com/images/M/MV5BMzUyNzE2NTgtNzM0Ny00YzBjLWJmZjAtMmMwYmE5YTg1MjEyXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BMzUyNzE2NTgtNzM0Ny00YzBjLWJmZjAtMmMwYmE5YTg1MjEyXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`,
    year: 2013,
    rating: `TV-Y7-FV`,
    duration: `4 Seasons • 97 Eps`,
    genres: ["Komedi","Aksiyon"],
    description: `Süper güçlere sahip Thunderman ailesinin sıradan görünmeye çalıştığı hayatı.`,
    playlistId: `pl-thundermans`,
    youtubePlaylistId: `PLOmUMd_oRO0uFCW9fmB8RrqF7lgOtN0p4`,
  },
  {
    id: `ltunescartoons`,
    title: `Looney Tunes Cartoons`,
    poster: `https://m.media-amazon.com/images/I/71lg8c9EZeL._AC_UF894,1000_QL80_.jpg`,
    backdrop: `https://m.media-amazon.com/images/I/71lg8c9EZeL._AC_UF894,1000_QL80_.jpg`,
    year: 2019,
    rating: `TV-PG`,
    duration: `5 Seasons • 200 Eps`,
    genres: ["Komedi"],
    description: `Bugs Bunny, Daffy Duck ve diğer sevilen karakterlerin yeni kısa animasyonları.`,
    playlistId: `pl-ltunescartoons`,
    youtubePlaylistId: `PL1Z6ttYZJTaMqSFfkTZDwQFt3Xpgodu2W`,
  },
  {
    id: `clarenceromania`,
    title: `Clarence Romania`,
    poster: `https://m.media-amazon.com/images/M/MV5BMjNhYWQ3ZjgtYWQ2Ny00MzQ4LWFiODgtMWJkZDYwYWE1NDZmXkEyXkFqcGc@._V1_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BMjNhYWQ3ZjgtYWQ2Ny00MzQ4LWFiODgtMWJkZDYwYWE1NDZmXkEyXkFqcGc@._V1_.jpg`,
    year: 2022,
    rating: `TV-Y7-FV`,
    duration: `3 Seasons • 106 Eps`,
    genres: ["Aksiyon","Gizem"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-clarenceromania`,
    youtubePlaylistId: `PLRbdoUts81DWI8w7bcqNZdeUVgMx0890x`,
  },
  {
    id: `scooby`,
    title: `Scooby Show`,
    poster: `https://licensing.biz/wp-content/uploads/2023/10/Scoobtober-569x1024.jpg`,
    backdrop: `https://licensing.biz/wp-content/uploads/2023/10/Scoobtober-569x1024.jpg`,
    year: 2022,
    rating: `TV-14`,
    duration: `1 Season • 49 Eps`,
    genres: ["Aksiyon","Gizem korku"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-scooby`,
    youtubePlaylistId: `PLTOeHiCTiZp1b7AlWiE4amd9AMRBMC`,
  },
  {
    id: `haloween`,
    title: `CN Halloween Special`,
    poster: `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNuhPN8CJpb-jtexxFyvoq2Fi8pT6dD1vqPA&s`,
    backdrop: `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNuhPN8CJpb-jtexxFyvoq2Fi8pT6dD1vqPA&s`,
    year: 2022,
    rating: `TV-14`,
    duration: `1 Season • 49 Eps`,
    genres: ["Aksiyon","Gizem korku"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-haloween`,
    youtubePlaylistId: `PLJRBd5RNL15EJD1ELg9HiUcYP6_rhaqWK`,
  },
  {
    id: `regularshow`,
    title: `Regular Show`,
    poster: `https://m.media-amazon.com/images/M/MV5BNDJlMGI1MDYtZDM0MS00NDYzLWIyMmUtZTY5MjY3MzJiN2QwXkEyXkFqcGc@._V1_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BNDJlMGI1MDYtZDM0MS00NDYzLWIyMmUtZTY5MjY3MzJiN2QwXkEyXkFqcGc@._V1_.jpg`,
    year: 2010,
    rating: `TV-Y7-FV`,
    duration: `1 Season • 49 Eps`,
    genres: ["Aksiyon","komedisi"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-regularshow`,
    youtubePlaylistId: `PLaj5S0F-5Vr-eQzftZnrC8spAfwZo1JQO`,
  },
  {
    id: `flapjack`,
    title: `FlapJack`,
    poster: `https://m.media-amazon.com/images/M/MV5BMTkzMDdiNGItYmZmYy00NDU0LWE5ZDMtZTgyNDc3ODgzNzM2XkEyXkFqcGc@._V1_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BMTkzMDdiNGItYmZmYy00NDU0LWE5ZDMtZTgyNDc3ODgzNzM2XkEyXkFqcGc@._V1_.jpg`,
    year: 2010,
    rating: `TV-PG`,
    duration: `1 Season • 49 Eps`,
    genres: ["Macera","Gizem"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-flapjack`,
    youtubePlaylistId: `PLkZ1r2KIV0fzUuG1EWlvXEYFiX5By02h2`,
  },
  {
    id: `gumball`,
    title: `Gumball`,
    poster: `https://m.media-amazon.com/images/M/MV5BNmEwYzNhODgtZDc2Yi00MDAyLTliNWYtMDRkMThmMWE0NGNkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BNmEwYzNhODgtZDc2Yi00MDAyLTliNWYtMDRkMThmMWE0NGNkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`,
    year: 2010,
    rating: `TV-PG`,
    duration: `1 Season • 49 Eps`,
    genres: ["Macera","Gizem"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-gumball`,
    youtubePlaylistId: `PLiR6LEIR8I0AeNLmoEbplwzELDMl6zaKu`,
  },
  {
    id: `ppg`,
    title: `Power Puff Girls`,
    poster: `https://m.media-amazon.com/images/M/MV5BMDI5NmQwZTUtNWI0Mi00MDE2LTkwNzQtMDFmZjRkM2Y1YjEwXkEyXkFqcGc@._V1_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BMDI5NmQwZTUtNWI0Mi00MDE2LTkwNzQtMDFmZjRkM2Y1YjEwXkEyXkFqcGc@._V1_.jpg`,
    year: 2010,
    rating: `TV-PG`,
    duration: `1 Season • 49 Eps`,
    genres: ["Macera","Gizem"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-ppg`,
    youtubePlaylistId: `PL258poKABt5Wx-YXePg6WfdKopiXxbibb`,
  },
  {
    id: `chowder`,
    title: `Chowder`,
    poster: `https://m.media-amazon.com/images/M/MV5BYTkxM2YzYTYtODY1OS00NjFjLWFiNTgtNDI0MjY4N2FkNjY5XkEyXkFqcGc@._V1_QL75_UY281_CR13,0,190,281_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BYTkxM2YzYTYtODY1OS00NjFjLWFiNTgtNDI0MjY4N2FkNjY5XkEyXkFqcGc@._V1_QL75_UY281_CR13,0,190,281_.jpg`,
    year: 2010,
    rating: `TV-PG`,
    duration: `1 Season • 49 Eps`,
    genres: ["Macera","Komedi"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-chowder`,
    youtubePlaylistId: `PL258poKABt5V6PzpqnlqD0aM937YU1bmq`,
  },
  {
    id: `cnhalloween`,
    title: `CN Halloween Time`,
    poster: `https://i.ebayimg.com/images/g/wXUAAOxyxU1Q9FlH/s-l640.jpg`,
    backdrop: `https://i.ebayimg.com/images/g/wXUAAOxyxU1Q9FlH/s-l640.jpg`,
    year: 2010,
    rating: `TV-14`,
    duration: `1 Season • 49 Eps`,
    genres: ["Macera","Gizem korku"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-cnhalloween`,
    youtubePlaylistId: `PL258poKABt5XNOWoAtRCQJKBMKAWMRdsQ`,
  },
  {
    id: `billyandmandy`,
    title: `The Grim Adventures of Billy and Mandy`,
    poster: `https://i.redd.it/v05l6wted5071.jpg`,
    backdrop: `https://i.redd.it/v05l6wted5071.jpg`,
    year: 2010,
    rating: `TV-14`,
    duration: `1 Season • 49 Eps`,
    genres: ["Macera","Gizem korku"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-billyandmandy`,
    youtubePlaylistId: `PLaK542wd-ut4O8KRF1aumS4GLa1AoBvSE`,
  },
  {
    id: `spongebob`,
    title: `SpongeBob SquarePants`,
    poster: `https://image.tmdb.org/t/p/original/zDuKxQkG8EemvLdBn43ChdM0MJL.jpg`,
    backdrop: `https://image.tmdb.org/t/p/original/zDuKxQkG8EemvLdBn43ChdM0MJL.jpg`,
    year: 2010,
    rating: `TV-PG`,
    duration: `1 Season • 49 Eps`,
    genres: ["Macera","Komedi"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-spongebob`,
    youtubePlaylistId: `PLXG4I392sUnODI37L4o1tp9SSu-oxTPAF`,
  },
  {
    id: `transformerscyber`,
    title: `Transformers: Cyberverse`,
    poster: `https://m.media-amazon.com/images/M/MV5BMTdkMDZiNjgtNGI0Yi00MmFmLTgyNzEtNTdmYjc3OWU3Y2I2XkEyXkFqcGc@._V1_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BMTdkMDZiNjgtNGI0Yi00MmFmLTgyNzEtNTdmYjc3OWU3Y2I2XkEyXkFqcGc@._V1_.jpg`,
    year: 2015,
    rating: `TV-Y7-FV`,
    duration: `1 Season • 49 Eps`,
    genres: ["Macera","Aksiyon"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-transformerscyber`,
    youtubePlaylistId: `PLiz2R-QaHSOt2tN9F8gmGL2vRHYGNQr-M`,
  },
  {
    id: `couragethecowardlydog`,
    title: `Courage the Cowardly Dog`,
    poster: `https://m.media-amazon.com/images/M/MV5BNDJiYjJlZTctYmFkMy00MDE0LTgyYmYtZTg3NjViZmY3MDc4XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BNDJiYjJlZTctYmFkMy00MDE0LTgyYmYtZTg3NjViZmY3MDc4XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`,
    year: 2015,
    rating: `TV-14`,
    duration: `1 Season • 49 Eps`,
    genres: ["Macera","Gizem korku"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-couragethecowardlydog`,
    youtubePlaylistId: `PLiz2R-QaHSOt58OUAucix0rxJ2OR9-ssc`,
  },
  {
    id: `phineas`,
    title: `Phineas and Ferb`,
    poster: `https://m.media-amazon.com/images/M/MV5BMTc1NjcxNzg4MF5BMl5BanBnXkFtZTgwOTMzNzgyMDE@._V1_FMjpg_UX1000_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BMTc1NjcxNzg4MF5BMl5BanBnXkFtZTgwOTMzNzgyMDE@._V1_FMjpg_UX1000_.jpg`,
    year: 2015,
    rating: `TV-PG`,
    duration: `1 Season • 49 Eps`,
    genres: ["Macera","Komedi"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-phineas`,
    youtubePlaylistId: `PLHBUmMjK-bVeW2PaKLYIiuY7h1FSP81NQ`,
  },
  {
    id: `yellowyeti`,
    title: `De Geweldige Yellow Yeti`,
    poster: `https://m.media-amazon.com/images/M/MV5BZDdjOTY2OTktMjdhMy00NTU1LTllZDktNTkzMDQyNTVkMjZmXkEyXkFqcGc@._V1_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BZDdjOTY2OTktMjdhMy00NTU1LTllZDktNTkzMDQyNTVkMjZmXkEyXkFqcGc@._V1_.jpg`,
    year: 2015,
    rating: `TV-PG`,
    duration: `1 Season • 49 Eps`,
    genres: ["Macera","Komedi"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-yellowyeti`,
    youtubePlaylistId: `PLHBUmMjK-bVdeDry56-lwTOTOUOlYV0pg`,
  },
  {
    id: `geestmolly`,
    title: `De Geest en Molly McGee`,
    poster: `https://static.filmvandaag.nl/shows/original/9000/9302.jpg?v=1&width=400`,
    backdrop: `https://static.filmvandaag.nl/shows/original/9000/9302.jpg?v=1&width=400`,
    year: 2015,
    rating: `TV-PG`,
    duration: `1 Season • 49 Eps`,
    genres: ["Macera","Komedi"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-geestmolly`,
    youtubePlaylistId: `PLHBUmMjK-bVdc_wyjWNHtn0VhZ-SQXTfM`,
  },
  {
    id: `stevenfuture`,
    title: `Steven Universe: Future`,
    poster: `https://m.media-amazon.com/images/M/MV5BZTAxMTY1ZDAtMmY0Yy00Mzk1LTk3MzItZTA3YjM1NTMxMmRiXkEyXkFqcGc@._V1_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BZTAxMTY1ZDAtMmY0Yy00Mzk1LTk3MzItZTA3YjM1NTMxMmRiXkEyXkFqcGc@._V1_.jpg`,
    year: 2015,
    rating: `TV-PG`,
    duration: `1 Season • 49 Eps`,
    genres: ["Macera","Komedi"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-stevenfuture`,
    youtubePlaylistId: `PLnnhPWO60cimwgwboYyB_1YIFQ5auCLTz`,
  },
  {
    id: `chowder`,
    title: `Chowder`,
    poster: `https://m.media-amazon.com/images/M/MV5BYTkxM2YzYTYtODY1OS00NjFjLWFiNTgtNDI0MjY4N2FkNjY5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BYTkxM2YzYTYtODY1OS00NjFjLWFiNTgtNDI0MjY4N2FkNjY5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`,
    year: 2015,
    rating: `TV-PG`,
    duration: `1 Season • 49 Eps`,
    genres: ["Macera","Komedi"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-chowder`,
    youtubePlaylistId: `PLLIU9nFd9IrE8gglrM_S7Js2OPqyk5eO_`,
  },
  {
    id: `villainous`,
    title: `Villainous`,
    poster: `https://upload.wikimedia.org/wikipedia/en/5/5c/VillainousMiniseriesOriginalCover.jpg`,
    backdrop: `https://upload.wikimedia.org/wikipedia/en/5/5c/VillainousMiniseriesOriginalCover.jpg`,
    year: 2015,
    rating: `TV-PG`,
    duration: `1 Season • 49 Eps`,
    genres: ["Macera","Komedi"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-villainous`,
    youtubePlaylistId: `PLx4owGbSBUxrv1Lb81k_i23RY2WwtDZ-Z`,
  },
  {
    id: `randy`,
    title: `Randy Cunningham: Nastoletni Ninja`,
    poster: `https://images.justwatch.com/poster/207531981/s718/randy-cunningham-9th-grade-ninja.jpg`,
    backdrop: `https://images.justwatch.com/poster/207531981/s718/randy-cunningham-9th-grade-ninja.jpg`,
    year: 2015,
    rating: `TV-PG`,
    duration: `1 Season • 49 Eps`,
    genres: ["Macera","Komedi"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-randy`,
    youtubePlaylistId: `PLlLYYUTQfvu00CD-uaQ3gwXTckKskq7Pu`,
  },
  {
    id: `kick`,
    title: `Kick Buttowski`,
    poster: `https://m.media-amazon.com/images/M/MV5BZTk3OGMwMWMtOWYwYS00MjUzLWJlY2EtNzUyOWExYmQ2ZTQ1XkEyXkFqcGc@._V1_QL75_UX190_CR0,2,190,281_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BZTk3OGMwMWMtOWYwYS00MjUzLWJlY2EtNzUyOWExYmQ2ZTQ1XkEyXkFqcGc@._V1_QL75_UX190_CR0,2,190,281_.jpg`,
    year: 2015,
    rating: `TV-PG`,
    duration: `1 Season • 49 Eps`,
    genres: ["Macera","Komedi"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-kick`,
    youtubePlaylistId: `PLE9ABE6A4D20BD9FD`,
  },
  {
    id: `ultimate`,
    title: `Ultimate Spider-Man`,
    poster: `https://m.media-amazon.com/images/M/MV5BMjFmOGZkYWQtMGQ4MC00NzRiLWI4ZTMtNDEwZDZiMDMyMzNmXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BMjFmOGZkYWQtMGQ4MC00NzRiLWI4ZTMtNDEwZDZiMDMyMzNmXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`,
    year: 2015,
    rating: `TV-PG`,
    duration: `1 Season • 49 Eps`,
    genres: ["Macera","Komedi"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-ultimate`,
    youtubePlaylistId: `PL9qXF14Xc9gLPJplbj-JXTJDgffVP2VZL`,
  },
  {
    id: `galaxy`,
    title: `Guardians of the Galaxy`,
    poster: `https://m.media-amazon.com/images/M/MV5BNDM4NDQxMDU2MV5BMl5BanBnXkFtZTgwMDY2MDQ5NjE@._V1_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BNDM4NDQxMDU2MV5BMl5BanBnXkFtZTgwMDY2MDQ5NjE@._V1_.jpg`,
    year: 2015,
    rating: `TV-PG`,
    duration: `1 Season • 49 Eps`,
    genres: ["Macera","Komedi"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-galaxy`,
    youtubePlaylistId: `PL9qXF14Xc9gLFaK97EYwqmjoZc7g_-8z9`,
  },
  {
    id: `bighero`,
    title: `Big Hero 6`,
    poster: `https://m.media-amazon.com/images/M/MV5BOTc3YTYwNTQtNzNmOC00YTg1LWJiNTgtYWU0ZjgyMzRjNDc2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BOTc3YTYwNTQtNzNmOC00YTg1LWJiNTgtYWU0ZjgyMzRjNDc2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`,
    year: 2015,
    rating: `TV-PG`,
    duration: `1 Season • 49 Eps`,
    genres: ["Macera","Komedi"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-bighero`,
    youtubePlaylistId: `PL9qXF14Xc9gJ8NTJanihD2kCa3jXPQHqx`,
  },
  {
    id: `ducks`,
    title: `La Bande à Picsou`,
    poster: `https://fr.web.img4.acsta.net/pictures/20/03/16/16/57/5441696.jpg`,
    backdrop: `https://fr.web.img4.acsta.net/pictures/20/03/16/16/57/5441696.jpg`,
    year: 2015,
    rating: `TV-PG`,
    duration: `1 Season • 49 Eps`,
    genres: ["Macera","Komedi"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-ducks`,
    youtubePlaylistId: `PLFCwHVG6gilNP-YQzgD9YPOU5nmlDO-UQ`,
  },
  {
    id: `bigdinasour`,
    title: `Moon Girl et Devil le Dinosaure`,
    poster: `https://m.media-amazon.com/images/M/MV5BMzViMTQ5ZGYtMmRjZC00OTVjLTkzMTEtMGMxMzlkNDc1OGQxXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BMzViMTQ5ZGYtMmRjZC00OTVjLTkzMTEtMGMxMzlkNDc1OGQxXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`,
    year: 2015,
    rating: `TV-PG`,
    duration: `1 Season • 49 Eps`,
    genres: ["Macera","Komedi"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-bigdinasour`,
    youtubePlaylistId: `PLFCwHVG6gilNLwChC5ZNs_7XlZ1Jcanqw`,
  },
  {
    id: `ghostforce`,
    title: `Ghost Force`,
    poster: `https://m.media-amazon.com/images/M/MV5BZGE3MDQ3OGEtMDEwMS00YTE3LWE1Y2YtZGFiYzE2MWU4Nzg5XkEyXkFqcGc@._V1_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BZGE3MDQ3OGEtMDEwMS00YTE3LWE1Y2YtZGFiYzE2MWU4Nzg5XkEyXkFqcGc@._V1_.jpg`,
    year: 2015,
    rating: `TV-PG`,
    duration: `1 Season • 49 Eps`,
    genres: ["Macera","Komedi"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-ghostforce`,
    youtubePlaylistId: `PLFCwHVG6gilP8m34GhDrS8ROablGcE4_T`,
  },
  {
    id: `distandlands`,
    title: `Adventure Time: Distant Lands`,
    poster: `https://resizing.flixster.com/DyT34YI3TO_5fp_CPLof6WUor-c=/ems.cHJkLWVtcy1hc3NldHMvdHZzZXJpZXMvUlRUVjkyMjk2Mi53ZWJw`,
    backdrop: `https://resizing.flixster.com/DyT34YI3TO_5fp_CPLof6WUor-c=/ems.cHJkLWVtcy1hc3NldHMvdHZzZXJpZXMvUlRUVjkyMjk2Mi53ZWJw`,
    year: 2010,
    rating: `TV-PG`,
    duration: `1 Season • 49 Eps`,
    genres: ["Macera","Gizem"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-distandlands`,
    youtubePlaylistId: `PLmEWbcIX2pqr1ia5IvNpukZiVGKvDOG5M`,
  },
  {
    id: `angelo-rules`,
    title: `Angelo Rules`,
    poster: `https://m.media-amazon.com/images/M/MV5BZTU4YWRlMTUtMWFmZS00ZDMzLTgwM2YtNjgwOTQ0ODA3MmRmXkEyXkFqcGc@._V1_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BZTU4YWRlMTUtMWFmZS00ZDMzLTgwM2YtNjgwOTQ0ODA3MmRmXkEyXkFqcGc@._V1_.jpg`,
    year: 2010,
    rating: `TV-PG`,
    duration: `1 Season • 49 Eps`,
    genres: ["Macera","Gizem"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-angelo-rules`,
    youtubePlaylistId: `PLEskFgfTPJn3E1kMX2RLhB5TsLrfpkLlK`,
  },
  {
    id: `maxs`,
    title: `Max & The Midknights `,
    poster: `https://m.media-amazon.com/images/M/MV5BYjJiMTM4ZjUtMDMzNi00NTAxLThhOTktNTk3M2IwNTQxYzJkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BYjJiMTM4ZjUtMDMzNi00NTAxLThhOTktNTk3M2IwNTQxYzJkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`,
    year: 2010,
    rating: `TV-PG`,
    duration: `1 Season • 49 Eps`,
    genres: ["Macera","Gizem"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-maxs`,
    youtubePlaylistId: `PLUQR09yEYrP19UtlDyc4-mNC1eGyy-VtX`,
  },
  {
    id: `generator-rex`,
    title: `Generator Rex`,
    poster: `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAA801bMLg1gxTDY9vVIW3tEyl3dP58n-KOQ&s`,
    backdrop: `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAA801bMLg1gxTDY9vVIW3tEyl3dP58n-KOQ&s`,
    year: 2010,
    rating: `TV-PG`,
    duration: `1 Season • 49 Eps`,
    genres: ["Macera","Gizem"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-generator-rex`,
    youtubePlaylistId: `PLeWt4i89tklqXah-0HBdGhszq__G0Eozb`,
  },
  {
    id: `fosters`,
    title: `Foster home for imaginary friends`,
    poster: `https://m.media-amazon.com/images/M/MV5BNTZjNzhkYjQtZDBhNS00NWM3LTk2NGUtZTkwODMyMTA4ZjdiXkEyXkFqcGc@._V1_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BNTZjNzhkYjQtZDBhNS00NWM3LTk2NGUtZTkwODMyMTA4ZjdiXkEyXkFqcGc@._V1_.jpg`,
    year: 2010,
    rating: `TV-PG`,
    duration: `1 Season • 49 Eps`,
    genres: ["Macera","Gizem"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-fosters`,
    youtubePlaylistId: `PL8ImJqzk7DAaA9mTiBYXh0Vs1oz9b3W2z`,
  },
  {
    id: `starwarsresistance`,
    title: `Star Wars: The Resistance`,
    poster: `https://m.media-amazon.com/images/M/MV5BMTkyMTc3NjAwNF5BMl5BanBnXkFtZTgwNTU1ODIyNjM@._V1_FMjpg_UX1000_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BMTkyMTc3NjAwNF5BMl5BanBnXkFtZTgwNTU1ODIyNjM@._V1_FMjpg_UX1000_.jpg`,
    year: 2010,
    rating: `TV-PG`,
    duration: `1 Season • 49 Eps`,
    genres: ["Macera","Gizem"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-starwarsresistance`,
    youtubePlaylistId: `PLXsbMnnbPpLUQmff9_ReAk8g8u92_6rJd`,
  },
  {
    id: `teentitans`,
    title: `Teen Titans`,
    poster: `https://m.media-amazon.com/images/M/MV5BOTg3NzY2MDQtMjUxNS00N2Q3LTkxODktMmU1NzdjZTNkMzQ0XkEyXkFqcGc@._V1_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BOTg3NzY2MDQtMjUxNS00N2Q3LTkxODktMmU1NzdjZTNkMzQ0XkEyXkFqcGc@._V1_.jpg`,
    year: 2010,
    rating: `TV-PG`,
    duration: `1 Season • 49 Eps`,
    genres: ["Macera","Gizem"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-teentitans`,
    youtubePlaylistId: `PLhiban91e2OqgVt6dccVkJ07t3bFv7uOx`,
  },
  {
    id: `minecraft story mode`,
    title: `Minecraft Story Mode`,
    poster: `https://m.media-amazon.com/images/M/MV5BZWNkN2NjNzUtMWU5OC00Mzk5LThlM2YtODJkYjdhNDFlOTQ4XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BZWNkN2NjNzUtMWU5OC00Mzk5LThlM2YtODJkYjdhNDFlOTQ4XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`,
    year: 2010,
    rating: `TV-PG`,
    duration: `1 Season • 49 Eps`,
    genres: ["Macera","Gizem"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-minecraft story mode`,
    youtubePlaylistId: `PLLsCJcWF3vVeGCgvvN06UbvT5IVXjHknN`,
  },
  {
    id: `beavis`,
    title: `Beavis and Butt-Head`,
    poster: `https://m.media-amazon.com/images/M/MV5BNzU3Mzk0ZTUtMmRkNS00MjI1LWEzNjYtNzI2MWJkN2JkNjc4XkEyXkFqcGc@._V1_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BNzU3Mzk0ZTUtMmRkNS00MjI1LWEzNjYtNzI2MWJkN2JkNjc4XkEyXkFqcGc@._V1_.jpg`,
    year: 2010,
    rating: `TV-PG`,
    duration: `1 Season • 49 Eps`,
    genres: ["Macera","Gizem"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-beavis`,
    youtubePlaylistId: `PLLHHcQWkLnprz8QqcuoNJ3apW2vsj0v8D`,
  },
  {
    id: `simpsons`,
    title: `The Simpsons`,
    poster: `https://images.justwatch.com/poster/307635545/s332/sezon-35.jpg`,
    backdrop: `https://images.justwatch.com/poster/307635545/s332/sezon-35.jpg`,
    year: 2010,
    rating: `TV-PG`,
    duration: `1 Season • 49 Eps`,
    genres: ["Macera","Gizem"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-simpsons`,
    youtubePlaylistId: `PLCVuwQ1eXVCWbQ06SrBiCZlB1Ci6qJdFw`,
  },
  {
    id: `robotchicken`,
    title: `Robot Chicken`,
    poster: `https://m.media-amazon.com/images/M/MV5BNmMxZWM5NzYtMTJkNS00YTA1LWE2MzYtNmI0NTQzOTRmODQ0XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BNmMxZWM5NzYtMTJkNS00YTA1LWE2MzYtNmI0NTQzOTRmODQ0XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`,
    year: 2010,
    rating: `TV-PG`,
    duration: `1 Season • 49 Eps`,
    genres: ["Macera","Gizem"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-robotchicken`,
    youtubePlaylistId: `PLG8ENTVyb-dfY_bOaciqr6bsXsKZq61_9`,
  },
  {
    id: `rickandmortysimpsons`,
    title: `Rick and Morty - Simpsons Universe Special`,
    poster: `https://mir-s3-cdn-cf.behance.net/project_modules/fs/e8cd9488239301.5dd0486ee11eb.jpg`,
    backdrop: `https://mir-s3-cdn-cf.behance.net/project_modules/fs/e8cd9488239301.5dd0486ee11eb.jpg`,
    year: 2010,
    rating: `TV-PG`,
    duration: `1 Season • 49 Eps`,
    genres: ["Macera","Gizem"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-rickandmortysimpsons`,
    youtubePlaylistId: `PLhSgw0LS-Vy9wvGRTJADhiOrlCAjNCMAN`,
  },
  {
    id: `familyguy`,
    title: `Family Guy`,
    poster: `https://m.media-amazon.com/images/M/MV5BNTZlMGQ1YjEtMzVlNC00ZmMxLTk0MzgtZjdkYTU1NmUxNTQ0XkEyXkFqcGc@._V1_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BNTZlMGQ1YjEtMzVlNC00ZmMxLTk0MzgtZjdkYTU1NmUxNTQ0XkEyXkFqcGc@._V1_.jpg`,
    year: 2010,
    rating: `TV-PG`,
    duration: `1 Season • 49 Eps`,
    genres: ["Macera","Gizem"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-familyguy`,
    youtubePlaylistId: `PLd3-CCCcbQeJ4A0MXjaOk3C_1ABIN3ICM`,
  },
  {
    id: `pokemon`,
    title: `Pokémon`,
    poster: `https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimages-wixmp-ed30a86b8c4ca887773594c2.wixmp.com%2Ff%2F57c7ed67-f9d0-47a8-82dc-7506d8128ea8%2Fdc3k9hx-bd8d5811-2cf9-4a0c-b266-986f375e4797.png%2Fv1%2Ffill%2Fw_777%2Ch_1029%2Cq_70%2Cstrp%2Fmy_pokemon_poster_gen_1_by_supermariocarlos_dc3k9hx-pre.jpg%3Ftoken%3DeyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MTM1NiIsInBhdGgiOiJcL2ZcLzU3YzdlZDY3LWY5ZDAtNDdhOC04MmRjLTc1MDZkODEyOGVhOFwvZGMzazloeC1iZDhkNTgxMS0yY2Y5LTRhMGMtYjI2Ni05ODZmMzc1ZTQ3OTcucG5nIiwid2lkdGgiOiI8PTEwMjQifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.kEyd8On5ohDzew3M24hFeSbDBPiPeur24TVT8A11nbc&f=1&nofb=1&ipt=9f794c9ff5846a0a60531b0309792481da42978b84c4ab324fd2dc655d3cadf5`,
    backdrop: `https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimages-wixmp-ed30a86b8c4ca887773594c2.wixmp.com%2Ff%2F57c7ed67-f9d0-47a8-82dc-7506d8128ea8%2Fdc3k9hx-bd8d5811-2cf9-4a0c-b266-986f375e4797.png%2Fv1%2Ffill%2Fw_777%2Ch_1029%2Cq_70%2Cstrp%2Fmy_pokemon_poster_gen_1_by_supermariocarlos_dc3k9hx-pre.jpg%3Ftoken%3DeyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MTM1NiIsInBhdGgiOiJcL2ZcLzU3YzdlZDY3LWY5ZDAtNDdhOC04MmRjLTc1MDZkODEyOGVhOFwvZGMzazloeC1iZDhkNTgxMS0yY2Y5LTRhMGMtYjI2Ni05ODZmMzc1ZTQ3OTcucG5nIiwid2lkdGgiOiI8PTEwMjQifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.kEyd8On5ohDzew3M24hFeSbDBPiPeur24TVT8A11nbc&f=1&nofb=1&ipt=9f794c9ff5846a0a60531b0309792481da42978b84c4ab324fd2dc655d3cadf5`,
    year: 2010,
    rating: `TV-PG`,
    duration: `1 Season • 49 Eps`,
    genres: ["Macera","Gizem"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-pokemon`,
    youtubePlaylistId: `PLo60BvbiWBuqUwSRFou3pbPV2IAWaP0rg`,
  },
  {
    id: `peanuts`,
    title: `Peanuts`,
    poster: `https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimages.justwatch.com%2Fposter%2F287913782%2Fs718%2Fdie-peanuts-classics.jpg&f=1&nofb=1&ipt=0adacddeb994d749ee4d953a3c7304b517eda939edf0b7bb40393889d9e92565`,
    backdrop: `https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimages.justwatch.com%2Fposter%2F287913782%2Fs718%2Fdie-peanuts-classics.jpg&f=1&nofb=1&ipt=0adacddeb994d749ee4d953a3c7304b517eda939edf0b7bb40393889d9e92565`,
    year: 2010,
    rating: `TV-PG`,
    duration: `1 Season • 49 Eps`,
    genres: ["Macera","Gizem"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-peanuts`,
    youtubePlaylistId: `PLLhOnau-tupQarwF3RjxwUV8Kr6UZONjv`,
  },
  {
    id: `nicktoons`,
    title: `NickToons Collection`,
    poster: `https://wad.nyc3.digitaloceanspaces.com/yourfiles/uploads/014963da899bbbab049e5b228b426196/KOLEKSIYONU-4.png`,
    backdrop: `https://wad.nyc3.digitaloceanspaces.com/yourfiles/uploads/014963da899bbbab049e5b228b426196/KOLEKSIYONU-4.png`,
    year: 2010,
    rating: `TV-PG`,
    duration: `1 Season • 49 Eps`,
    genres: ["Koleksiyon"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-nicktoons`,
    youtubePlaylistId: `PLJb1AL9zU1Gpmo3_TKD7mG4MmzuhuPE0d`,
  },
  {
    id: `cartoonnetwork`,
    title: `Cartoon Network Collection`,
    poster: `https://wad.nyc3.digitaloceanspaces.com/yourfiles/uploads/706be073ad50f9598c060a6223217220/KOLEKSIYONU-3.png`,
    backdrop: `https://wad.nyc3.digitaloceanspaces.com/yourfiles/uploads/706be073ad50f9598c060a6223217220/KOLEKSIYONU-3.png`,
    year: 2010,
    rating: `TV-PG`,
    duration: `1 Season • 49 Eps`,
    genres: ["Koleksiyon"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-cartoonnetwork`,
    youtubePlaylistId: `PLZjNMNd2gTe5E6VQR04WVBsjvkDzVUBpw`,
  },
];

export const SHOW_PLAYLISTS: Playlist[] = [
  {
    id: `pl-gumball`,
    title: `The Amazing World of Gumball — Season 1`,
    description: `240 episodes across 6 seasons.`,
    episodes: makeEpisodes(`gumball`, `The Amazing World of Gumball`, 30, `https://m.media-amazon.com/images/M/MV5BNmEwYzNhODgtZDc2Yi00MDAyLTliNWYtMDRkMThmMWE0NGNkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`),
  },
  {
    id: `pl-theloudhouse`,
    title: `The Loud House — Season 1`,
    description: `130 episodes across 7 seasons.`,
    episodes: makeEpisodes(`theloudhouse`, `The Loud House`, 30, `https://m.media-amazon.com/images/M/MV5BZjlkMmQ5YzItZGRmMy00NjVjLWIwYmMtMzJjM2QxM2Q1OThkXkEyXkFqcGc@._V1_.jpg`),
  },
  {
    id: `pl-ben10ultimatealien`,
    title: `Ben 10 Alien Force — Season 1`,
    description: `46 episodes across 3 seasons.`,
    episodes: makeEpisodes(`ben10ultimatealien`, `Ben 10 Alien Force`, 30, `https://m.media-amazon.com/images/M/MV5BOGQ5YWFjYjItODE5OC00ZDQxLTk5ZmYtNzY0YzM4NjIyMWFlXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`),
  },
  {
    id: `pl-beastboy`,
    title: `Beast Boy Lone Wolf — Season 1`,
    description: `38 episodes across 1 season.`,
    episodes: makeEpisodes(`beastboy`, `Beast Boy Lone Wolf`, 30, `https://m.media-amazon.com/images/M/MV5BYzQxY2FjOWItNjc0Mi00NGNjLTg5NGYtNDBhNzdjMDBmN2Q4XkEyXkFqcGc@._V1_.jpg`),
  },
  {
    id: `pl-SpongeBobSquarePants`,
    title: `SpongeBob SquarePants Haloween — Season 1`,
    description: `280 episodes across 14 seasons.`,
    episodes: makeEpisodes(`SpongeBobSquarePants`, `SpongeBob SquarePants Haloween`, 30, `https://m.media-amazon.com/images/M/MV5BYjJmMjBkZjMtZThiZS00Nzk3LWJlN2UtYmE5ZjkyNjJiZjgxXkEyXkFqcGc@._V1_QL75_UY281_CR1,0,190,281_.jpg`),
  },
  {
    id: `pl-RegularShowLostTapes`,
    title: `Regular Show lost Tapes — Season 1`,
    description: `261 episodes across 8 seasons.`,
    episodes: makeEpisodes(`RegularShowLostTapes`, `Regular Show lost Tapes`, 30, `https://m.media-amazon.com/images/M/MV5BNDY5ZTA4ZGQtMzE2Ni00YjQ1LTk4ODktZGQwYTgwYWYxNjUwXkEyXkFqcGc@._V1_.jpg`),
  },
  {
    id: `pl-AdventureTime`,
    title: `Adventure Time — Season 1`,
    description: `283 episodes across 10 seasons.`,
    episodes: makeEpisodes(`AdventureTime`, `Adventure Time`, 30, `https://occ-0-753-1007.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABRV_sMrvu3tWVViD3FG-maRs7pdM01pKVjISgK7zVIeTEQTF0E0gX2VGS-crJoN5YxzYRZIZrKfCG2W26ZRo34i3acw6fdOzwkFr6YJbYufEGQM0v8be2W-M8da2L9HC.jpg?r=7fb`),
  },
  {
    id: `pl-MutantNinjaTurtles`,
    title: `Teenage Mutant Ninja Turtles — Season 1`,
    description: `124 episodes across 5 seasons.`,
    episodes: makeEpisodes(`MutantNinjaTurtles`, `Teenage Mutant Ninja Turtles`, 30, `https://m.media-amazon.com/images/M/MV5BZTA0ZTlkMGItNTJmYy00YTVkLTgwMDktZTJiNTE5NmQ0ZWI4XkEyXkFqcGc@._V1_.jpg`),
  },
  {
    id: `pl-TransformersEarthSpark`,
    title: `Transformers EarthSpark — Season 1`,
    description: `26 episodes across 2 seasons.`,
    episodes: makeEpisodes(`TransformersEarthSpark`, `Transformers EarthSpark`, 26, `https://m.media-amazon.com/images/M/MV5BNjAxNmRhZjctYTk1Ni00MGJjLThkY2YtNjdmODJjYTMwOGJlXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`),
  },
  {
    id: `pl-Ninjago`,
    title: `Ninjago — Season 1`,
    description: `200 episodes across 15 seasons.`,
    episodes: makeEpisodes(`Ninjago`, `Ninjago`, 30, `https://ninjagoizlesene.com.tr/wp-content/uploads/2026/03/Crystalized-Poster-scaled.jpg`),
  },
  {
    id: `pl-gravityfalls`,
    title: `Gravity Falls — Season 1`,
    description: `40 episodes across 2 seasons.`,
    episodes: makeEpisodes(`gravityfalls`, `Gravity Falls`, 30, `https://m.media-amazon.com/images/I/917WCiqRo6L._AC_UF1000,1000_QL80_.jpg`),
  },
  {
    id: `pl-stevenuniverse`,
    title: `Steven Universe — Season 1`,
    description: `160 episodes across 5 seasons.`,
    episodes: makeEpisodes(`stevenuniverse`, `Steven Universe`, 30, `https://m.media-amazon.com/images/M/MV5BZGJjMmI3ZDMtZTgyNi00MTZhLWE2ZjAtN2Q4YTUyMTg4OGY1XkEyXkFqcGc@._V1_.jpg`),
  },
  {
    id: `pl-FairlyOdd`,
    title: `The Fairly OddParents — Season 1`,
    description: `172 episodes across 10 seasons.`,
    episodes: makeEpisodes(`FairlyOdd`, `The Fairly OddParents`, 30, `https://m.media-amazon.com/images/M/MV5BY2RlNWMwZmUtMjM4MC00MDczLTk3NjktYTg2OTNiNThhNmNhXkEyXkFqcGc@._V1_.jpg`),
  },
  {
    id: `pl-clarence`,
    title: `Clarence — Season 1`,
    description: `121 episodes across 3 seasons.`,
    episodes: makeEpisodes(`clarence`, `Clarence`, 30, `https://m.media-amazon.com/images/M/MV5BMjNhYWQ3ZjgtYWQ2Ny00MzQ4LWFiODgtMWJkZDYwYWE1NDZmXkEyXkFqcGc@._V1_.jpg`),
  },
  {
    id: `pl-mira`,
    title: `Miraculous Ladybug — Season 1`,
    description: `130 episodes across 5 seasons.`,
    episodes: makeEpisodes(`mira`, `Miraculous Ladybug`, 30, `https://image.tmdb.org/t/p/w500/mwAJcSPtuRddU8AeL9lup5jE0Bn.jpg`),
  },
  {
    id: `pl-codename`,
    title: `Codename: Kids Next Door Shorts — Season 1`,
    description: `78 episodes across 6 seasons.`,
    episodes: makeEpisodes(`codename`, `Codename: Kids Next Door Shorts`, 30, `https://www.tvtime.com/_next/image?url=https%3A%2F%2Fartworks.thetvdb.com%2Fbanners%2Fposters%2F71685-2.jpg&w=640&q=75`),
  },
  {
    id: `pl-circus`,
    title: `The Amazing Digital Circus — Season 1`,
    description: `6 episodes across 1 season.`,
    episodes: makeEpisodes(`circus`, `The Amazing Digital Circus`, 6, `https://fr.web.img5.acsta.net/c_310_420/img/e0/d1/e0d113764c9c629f20a681041ab4e01c.jpg`),
  },
  {
    id: `pl-sonicprime`,
    title: `Sonic Prime — Season 1`,
    description: `24 episodes across 3 seasons.`,
    episodes: makeEpisodes(`sonicprime`, `Sonic Prime`, 24, `https://preview.redd.it/what-makes-sonic-prime-forgettable-than-the-other-sonic-v0-vka3qbs2w7ye1.png?width=640&crop=smart&auto=webp&s=3dd7cbb9b2bacdd621b34b37d25904ca536ab061`),
  },
  {
    id: `pl-ttg`,
    title: `Teen Titans Go! — Season 1`,
    description: `350 episodes across 8 seasons.`,
    episodes: makeEpisodes(`ttg`, `Teen Titans Go!`, 30, `https://m.media-amazon.com/images/M/MV5BMjE5MjMzOTc1Ml5BMl5BanBnXkFtZTcwNDQxMDY5OQ@@._V1_FMjpg_UX1000_.jpg`),
  },
  {
    id: `pl-kiff`,
    title: `Kiff — Season 1`,
    description: `20 episodes across 2 seasons.`,
    episodes: makeEpisodes(`kiff`, `Kiff`, 20, `https://m.media-amazon.com/images/M/MV5BMjA1NjIwNTMtY2Q2Ny00ZmVjLThkODItODg1ZjJmN2FjMDUzXkEyXkFqcGc@._V1_.jpg`),
  },
  {
    id: `pl-tomandjerry`,
    title: `Tom and Jerry — Season 1`,
    description: `161 episodes across 1 season.`,
    episodes: makeEpisodes(`tomandjerry`, `Tom and Jerry`, 30, `https://m.media-amazon.com/images/M/MV5BODY2YWI1OTAtY2FhZS00MGI1LTk0YjUtYmE3MDk0OGFkMWUyXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`),
  },
  {
    id: `pl-batmanunlimited`,
    title: `Batman Unlimited — Season 1`,
    description: `10 episodes across 1 season.`,
    episodes: makeEpisodes(`batmanunlimited`, `Batman Unlimited`, 10, `https://play-lh.googleusercontent.com/RWN0fec0a0lc8Y-VBfDHcnN-L3OrwE-xcu3SN0dQ8UWrdpn_B-LI0OxnHOKXZysB5hPZ`),
  },
  {
    id: `pl-thundermans`,
    title: `The Thundermans — Season 1`,
    description: `97 episodes across 4 seasons.`,
    episodes: makeEpisodes(`thundermans`, `The Thundermans`, 30, `https://m.media-amazon.com/images/M/MV5BMzUyNzE2NTgtNzM0Ny00YzBjLWJmZjAtMmMwYmE5YTg1MjEyXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`),
  },
  {
    id: `pl-ltunescartoons`,
    title: `Looney Tunes Cartoons — Season 1`,
    description: `200 episodes across 5 seasons.`,
    episodes: makeEpisodes(`ltunescartoons`, `Looney Tunes Cartoons`, 30, `https://m.media-amazon.com/images/I/71lg8c9EZeL._AC_UF894,1000_QL80_.jpg`),
  },
  {
    id: `pl-clarenceromania`,
    title: `Clarence Romania — Season 1`,
    description: `106 episodes across 3 seasons.`,
    episodes: makeEpisodes(`clarenceromania`, `Clarence Romania`, 30, `https://m.media-amazon.com/images/M/MV5BMjNhYWQ3ZjgtYWQ2Ny00MzQ4LWFiODgtMWJkZDYwYWE1NDZmXkEyXkFqcGc@._V1_.jpg`),
  },
  {
    id: `pl-scooby`,
    title: `Scooby Show — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`scooby`, `Scooby Show`, 30, `https://licensing.biz/wp-content/uploads/2023/10/Scoobtober-569x1024.jpg`),
  },
  {
    id: `pl-haloween`,
    title: `CN Halloween Special — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`haloween`, `CN Halloween Special`, 30, `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNuhPN8CJpb-jtexxFyvoq2Fi8pT6dD1vqPA&s`),
  },
  {
    id: `pl-regularshow`,
    title: `Regular Show — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`regularshow`, `Regular Show`, 30, `https://m.media-amazon.com/images/M/MV5BNDJlMGI1MDYtZDM0MS00NDYzLWIyMmUtZTY5MjY3MzJiN2QwXkEyXkFqcGc@._V1_.jpg`),
  },
  {
    id: `pl-flapjack`,
    title: `FlapJack — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`flapjack`, `FlapJack`, 30, `https://m.media-amazon.com/images/M/MV5BMTkzMDdiNGItYmZmYy00NDU0LWE5ZDMtZTgyNDc3ODgzNzM2XkEyXkFqcGc@._V1_.jpg`),
  },
  {
    id: `pl-gumball`,
    title: `Gumball — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`gumball`, `Gumball`, 30, `https://m.media-amazon.com/images/M/MV5BNmEwYzNhODgtZDc2Yi00MDAyLTliNWYtMDRkMThmMWE0NGNkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`),
  },
  {
    id: `pl-ppg`,
    title: `Power Puff Girls — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`ppg`, `Power Puff Girls`, 30, `https://m.media-amazon.com/images/M/MV5BMDI5NmQwZTUtNWI0Mi00MDE2LTkwNzQtMDFmZjRkM2Y1YjEwXkEyXkFqcGc@._V1_.jpg`),
  },
  {
    id: `pl-chowder`,
    title: `Chowder — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`chowder`, `Chowder`, 30, `https://m.media-amazon.com/images/M/MV5BYTkxM2YzYTYtODY1OS00NjFjLWFiNTgtNDI0MjY4N2FkNjY5XkEyXkFqcGc@._V1_QL75_UY281_CR13,0,190,281_.jpg`),
  },
  {
    id: `pl-cnhalloween`,
    title: `CN Halloween Time — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`cnhalloween`, `CN Halloween Time`, 30, `https://i.ebayimg.com/images/g/wXUAAOxyxU1Q9FlH/s-l640.jpg`),
  },
  {
    id: `pl-billyandmandy`,
    title: `The Grim Adventures of Billy and Mandy — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`billyandmandy`, `The Grim Adventures of Billy and Mandy`, 30, `https://i.redd.it/v05l6wted5071.jpg`),
  },
  {
    id: `pl-spongebob`,
    title: `SpongeBob SquarePants — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`spongebob`, `SpongeBob SquarePants`, 30, `https://image.tmdb.org/t/p/original/zDuKxQkG8EemvLdBn43ChdM0MJL.jpg`),
  },
  {
    id: `pl-transformerscyber`,
    title: `Transformers: Cyberverse — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`transformerscyber`, `Transformers: Cyberverse`, 30, `https://m.media-amazon.com/images/M/MV5BMTdkMDZiNjgtNGI0Yi00MmFmLTgyNzEtNTdmYjc3OWU3Y2I2XkEyXkFqcGc@._V1_.jpg`),
  },
  {
    id: `pl-couragethecowardlydog`,
    title: `Courage the Cowardly Dog — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`couragethecowardlydog`, `Courage the Cowardly Dog`, 30, `https://m.media-amazon.com/images/M/MV5BNDJiYjJlZTctYmFkMy00MDE0LTgyYmYtZTg3NjViZmY3MDc4XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`),
  },
  {
    id: `pl-phineas`,
    title: `Phineas and Ferb — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`phineas`, `Phineas and Ferb`, 30, `https://m.media-amazon.com/images/M/MV5BMTc1NjcxNzg4MF5BMl5BanBnXkFtZTgwOTMzNzgyMDE@._V1_FMjpg_UX1000_.jpg`),
  },
  {
    id: `pl-yellowyeti`,
    title: `De Geweldige Yellow Yeti — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`yellowyeti`, `De Geweldige Yellow Yeti`, 30, `https://m.media-amazon.com/images/M/MV5BZDdjOTY2OTktMjdhMy00NTU1LTllZDktNTkzMDQyNTVkMjZmXkEyXkFqcGc@._V1_.jpg`),
  },
  {
    id: `pl-geestmolly`,
    title: `De Geest en Molly McGee — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`geestmolly`, `De Geest en Molly McGee`, 30, `https://static.filmvandaag.nl/shows/original/9000/9302.jpg?v=1&width=400`),
  },
  {
    id: `pl-stevenfuture`,
    title: `Steven Universe: Future — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`stevenfuture`, `Steven Universe: Future`, 30, `https://m.media-amazon.com/images/M/MV5BZTAxMTY1ZDAtMmY0Yy00Mzk1LTk3MzItZTA3YjM1NTMxMmRiXkEyXkFqcGc@._V1_.jpg`),
  },
  {
    id: `pl-chowder`,
    title: `Chowder — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`chowder`, `Chowder`, 30, `https://m.media-amazon.com/images/M/MV5BYTkxM2YzYTYtODY1OS00NjFjLWFiNTgtNDI0MjY4N2FkNjY5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`),
  },
  {
    id: `pl-villainous`,
    title: `Villainous — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`villainous`, `Villainous`, 30, `https://upload.wikimedia.org/wikipedia/en/5/5c/VillainousMiniseriesOriginalCover.jpg`),
  },
  {
    id: `pl-randy`,
    title: `Randy Cunningham: Nastoletni Ninja — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`randy`, `Randy Cunningham: Nastoletni Ninja`, 30, `https://images.justwatch.com/poster/207531981/s718/randy-cunningham-9th-grade-ninja.jpg`),
  },
  {
    id: `pl-kick`,
    title: `Kick Buttowski — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`kick`, `Kick Buttowski`, 30, `https://m.media-amazon.com/images/M/MV5BZTk3OGMwMWMtOWYwYS00MjUzLWJlY2EtNzUyOWExYmQ2ZTQ1XkEyXkFqcGc@._V1_QL75_UX190_CR0,2,190,281_.jpg`),
  },
  {
    id: `pl-ultimate`,
    title: `Ultimate Spider-Man — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`ultimate`, `Ultimate Spider-Man`, 30, `https://m.media-amazon.com/images/M/MV5BMjFmOGZkYWQtMGQ4MC00NzRiLWI4ZTMtNDEwZDZiMDMyMzNmXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`),
  },
  {
    id: `pl-galaxy`,
    title: `Guardians of the Galaxy — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`galaxy`, `Guardians of the Galaxy`, 30, `https://m.media-amazon.com/images/M/MV5BNDM4NDQxMDU2MV5BMl5BanBnXkFtZTgwMDY2MDQ5NjE@._V1_.jpg`),
  },
  {
    id: `pl-bighero`,
    title: `Big Hero 6 — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`bighero`, `Big Hero 6`, 30, `https://m.media-amazon.com/images/M/MV5BOTc3YTYwNTQtNzNmOC00YTg1LWJiNTgtYWU0ZjgyMzRjNDc2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`),
  },
  {
    id: `pl-ducks`,
    title: `La Bande à Picsou — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`ducks`, `La Bande à Picsou`, 30, `https://fr.web.img4.acsta.net/pictures/20/03/16/16/57/5441696.jpg`),
  },
  {
    id: `pl-bigdinasour`,
    title: `Moon Girl et Devil le Dinosaure — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`bigdinasour`, `Moon Girl et Devil le Dinosaure`, 30, `https://m.media-amazon.com/images/M/MV5BMzViMTQ5ZGYtMmRjZC00OTVjLTkzMTEtMGMxMzlkNDc1OGQxXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`),
  },
  {
    id: `pl-ghostforce`,
    title: `Ghost Force — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`ghostforce`, `Ghost Force`, 30, `https://m.media-amazon.com/images/M/MV5BZGE3MDQ3OGEtMDEwMS00YTE3LWE1Y2YtZGFiYzE2MWU4Nzg5XkEyXkFqcGc@._V1_.jpg`),
  },
  {
    id: `pl-distandlands`,
    title: `Adventure Time: Distant Lands — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`distandlands`, `Adventure Time: Distant Lands`, 30, `https://resizing.flixster.com/DyT34YI3TO_5fp_CPLof6WUor-c=/ems.cHJkLWVtcy1hc3NldHMvdHZzZXJpZXMvUlRUVjkyMjk2Mi53ZWJw`),
  },
  {
    id: `pl-angelo-rules`,
    title: `Angelo Rules — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`angelo-rules`, `Angelo Rules`, 30, `https://m.media-amazon.com/images/M/MV5BZTU4YWRlMTUtMWFmZS00ZDMzLTgwM2YtNjgwOTQ0ODA3MmRmXkEyXkFqcGc@._V1_.jpg`),
  },
  {
    id: `pl-maxs`,
    title: `Max & The Midknights  — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`maxs`, `Max & The Midknights `, 30, `https://m.media-amazon.com/images/M/MV5BYjJiMTM4ZjUtMDMzNi00NTAxLThhOTktNTk3M2IwNTQxYzJkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`),
  },
  {
    id: `pl-generator-rex`,
    title: `Generator Rex — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`generator-rex`, `Generator Rex`, 30, `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAA801bMLg1gxTDY9vVIW3tEyl3dP58n-KOQ&s`),
  },
  {
    id: `pl-fosters`,
    title: `Foster home for imaginary friends — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`fosters`, `Foster home for imaginary friends`, 30, `https://m.media-amazon.com/images/M/MV5BNTZjNzhkYjQtZDBhNS00NWM3LTk2NGUtZTkwODMyMTA4ZjdiXkEyXkFqcGc@._V1_.jpg`),
  },
  {
    id: `pl-starwarsresistance`,
    title: `Star Wars: The Resistance — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`starwarsresistance`, `Star Wars: The Resistance`, 30, `https://m.media-amazon.com/images/M/MV5BMTkyMTc3NjAwNF5BMl5BanBnXkFtZTgwNTU1ODIyNjM@._V1_FMjpg_UX1000_.jpg`),
  },
  {
    id: `pl-teentitans`,
    title: `Teen Titans — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`teentitans`, `Teen Titans`, 30, `https://m.media-amazon.com/images/M/MV5BOTg3NzY2MDQtMjUxNS00N2Q3LTkxODktMmU1NzdjZTNkMzQ0XkEyXkFqcGc@._V1_.jpg`),
  },
  {
    id: `pl-minecraft story mode`,
    title: `Minecraft Story Mode — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`minecraft story mode`, `Minecraft Story Mode`, 30, `https://m.media-amazon.com/images/M/MV5BZWNkN2NjNzUtMWU5OC00Mzk5LThlM2YtODJkYjdhNDFlOTQ4XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`),
  },
  {
    id: `pl-beavis`,
    title: `Beavis and Butt-Head — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`beavis`, `Beavis and Butt-Head`, 30, `https://m.media-amazon.com/images/M/MV5BNzU3Mzk0ZTUtMmRkNS00MjI1LWEzNjYtNzI2MWJkN2JkNjc4XkEyXkFqcGc@._V1_.jpg`),
  },
  {
    id: `pl-simpsons`,
    title: `The Simpsons — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`simpsons`, `The Simpsons`, 30, `https://images.justwatch.com/poster/307635545/s332/sezon-35.jpg`),
  },
  {
    id: `pl-robotchicken`,
    title: `Robot Chicken — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`robotchicken`, `Robot Chicken`, 30, `https://m.media-amazon.com/images/M/MV5BNmMxZWM5NzYtMTJkNS00YTA1LWE2MzYtNmI0NTQzOTRmODQ0XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`),
  },
  {
    id: `pl-rickandmortysimpsons`,
    title: `Rick and Morty - Simpsons Universe Special — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`rickandmortysimpsons`, `Rick and Morty - Simpsons Universe Special`, 30, `https://mir-s3-cdn-cf.behance.net/project_modules/fs/e8cd9488239301.5dd0486ee11eb.jpg`),
  },
  {
    id: `pl-familyguy`,
    title: `Family Guy — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`familyguy`, `Family Guy`, 30, `https://m.media-amazon.com/images/M/MV5BNTZlMGQ1YjEtMzVlNC00ZmMxLTk0MzgtZjdkYTU1NmUxNTQ0XkEyXkFqcGc@._V1_.jpg`),
  },
  {
    id: `pl-pokemon`,
    title: `Pokémon — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`pokemon`, `Pokémon`, 30, `https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimages-wixmp-ed30a86b8c4ca887773594c2.wixmp.com%2Ff%2F57c7ed67-f9d0-47a8-82dc-7506d8128ea8%2Fdc3k9hx-bd8d5811-2cf9-4a0c-b266-986f375e4797.png%2Fv1%2Ffill%2Fw_777%2Ch_1029%2Cq_70%2Cstrp%2Fmy_pokemon_poster_gen_1_by_supermariocarlos_dc3k9hx-pre.jpg%3Ftoken%3DeyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MTM1NiIsInBhdGgiOiJcL2ZcLzU3YzdlZDY3LWY5ZDAtNDdhOC04MmRjLTc1MDZkODEyOGVhOFwvZGMzazloeC1iZDhkNTgxMS0yY2Y5LTRhMGMtYjI2Ni05ODZmMzc1ZTQ3OTcucG5nIiwid2lkdGgiOiI8PTEwMjQifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.kEyd8On5ohDzew3M24hFeSbDBPiPeur24TVT8A11nbc&f=1&nofb=1&ipt=9f794c9ff5846a0a60531b0309792481da42978b84c4ab324fd2dc655d3cadf5`),
  },
  {
    id: `pl-peanuts`,
    title: `Peanuts — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`peanuts`, `Peanuts`, 30, `https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimages.justwatch.com%2Fposter%2F287913782%2Fs718%2Fdie-peanuts-classics.jpg&f=1&nofb=1&ipt=0adacddeb994d749ee4d953a3c7304b517eda939edf0b7bb40393889d9e92565`),
  },
  {
    id: `pl-nicktoons`,
    title: `NickToons Collection — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`nicktoons`, `NickToons Collection`, 30, `https://wad.nyc3.digitaloceanspaces.com/yourfiles/uploads/014963da899bbbab049e5b228b426196/KOLEKSIYONU-4.png`),
  },
  {
    id: `pl-cartoonnetwork`,
    title: `Cartoon Network Collection — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`cartoonnetwork`, `Cartoon Network Collection`, 30, `https://wad.nyc3.digitaloceanspaces.com/yourfiles/uploads/706be073ad50f9598c060a6223217220/KOLEKSIYONU-3.png`),
  },
];

export const SHOW_CATEGORIES: MovieCategory[] = [
  {
    id: "trending",
    title: "Trending Now",
    movies: [SHOW_MOVIES[0], SHOW_MOVIES[1], SHOW_MOVIES[2], SHOW_MOVIES[3], SHOW_MOVIES[4], SHOW_MOVIES[5], SHOW_MOVIES[6], SHOW_MOVIES[7], SHOW_MOVIES[8], SHOW_MOVIES[9]],
  },
  {
    id: `komedi`,
    title: `Komedi`,
    movies: [SHOW_MOVIES[0], SHOW_MOVIES[1], SHOW_MOVIES[4], SHOW_MOVIES[5], SHOW_MOVIES[10], SHOW_MOVIES[12], SHOW_MOVIES[13], SHOW_MOVIES[15], SHOW_MOVIES[16], SHOW_MOVIES[18], SHOW_MOVIES[19], SHOW_MOVIES[20], SHOW_MOVIES[22], SHOW_MOVIES[23], SHOW_MOVIES[31], SHOW_MOVIES[34], SHOW_MOVIES[37], SHOW_MOVIES[38], SHOW_MOVIES[39], SHOW_MOVIES[40], SHOW_MOVIES[41], SHOW_MOVIES[42], SHOW_MOVIES[43], SHOW_MOVIES[44], SHOW_MOVIES[45], SHOW_MOVIES[46], SHOW_MOVIES[47], SHOW_MOVIES[48], SHOW_MOVIES[49], SHOW_MOVIES[50]],
  },
  {
    id: `macera`,
    title: `Macera`,
    movies: [SHOW_MOVIES[0], SHOW_MOVIES[1], SHOW_MOVIES[2], SHOW_MOVIES[3], SHOW_MOVIES[4], SHOW_MOVIES[5], SHOW_MOVIES[6], SHOW_MOVIES[7], SHOW_MOVIES[9], SHOW_MOVIES[11], SHOW_MOVIES[13], SHOW_MOVIES[14], SHOW_MOVIES[15], SHOW_MOVIES[17], SHOW_MOVIES[28], SHOW_MOVIES[29], SHOW_MOVIES[30], SHOW_MOVIES[31], SHOW_MOVIES[32], SHOW_MOVIES[33], SHOW_MOVIES[34], SHOW_MOVIES[35], SHOW_MOVIES[36], SHOW_MOVIES[37], SHOW_MOVIES[38], SHOW_MOVIES[39], SHOW_MOVIES[40], SHOW_MOVIES[41], SHOW_MOVIES[42], SHOW_MOVIES[43], SHOW_MOVIES[44], SHOW_MOVIES[45], SHOW_MOVIES[46], SHOW_MOVIES[47], SHOW_MOVIES[48], SHOW_MOVIES[49], SHOW_MOVIES[50], SHOW_MOVIES[51], SHOW_MOVIES[52], SHOW_MOVIES[53], SHOW_MOVIES[54], SHOW_MOVIES[55], SHOW_MOVIES[56], SHOW_MOVIES[57], SHOW_MOVIES[58], SHOW_MOVIES[59], SHOW_MOVIES[60], SHOW_MOVIES[61], SHOW_MOVIES[62], SHOW_MOVIES[63], SHOW_MOVIES[64], SHOW_MOVIES[65]],
  },
  {
    id: `aksiyon`,
    title: `Aksiyon`,
    movies: [SHOW_MOVIES[2], SHOW_MOVIES[3], SHOW_MOVIES[7], SHOW_MOVIES[8], SHOW_MOVIES[9], SHOW_MOVIES[17], SHOW_MOVIES[18], SHOW_MOVIES[21], SHOW_MOVIES[22], SHOW_MOVIES[24], SHOW_MOVIES[25], SHOW_MOVIES[26], SHOW_MOVIES[27], SHOW_MOVIES[35]],
  },
  {
    id: `fantezi`,
    title: `Fantezi`,
    movies: [SHOW_MOVIES[6], SHOW_MOVIES[12]],
  },
  {
    id: `gizem`,
    title: `Gizem`,
    movies: [SHOW_MOVIES[10], SHOW_MOVIES[16], SHOW_MOVIES[24], SHOW_MOVIES[28], SHOW_MOVIES[29], SHOW_MOVIES[30], SHOW_MOVIES[51], SHOW_MOVIES[52], SHOW_MOVIES[53], SHOW_MOVIES[54], SHOW_MOVIES[55], SHOW_MOVIES[56], SHOW_MOVIES[57], SHOW_MOVIES[58], SHOW_MOVIES[59], SHOW_MOVIES[60], SHOW_MOVIES[61], SHOW_MOVIES[62], SHOW_MOVIES[63], SHOW_MOVIES[64], SHOW_MOVIES[65]],
  },
  {
    id: `gizem-korku`,
    title: `Gizem korku`,
    movies: [SHOW_MOVIES[25], SHOW_MOVIES[26], SHOW_MOVIES[32], SHOW_MOVIES[33], SHOW_MOVIES[36]],
  },
  {
    id: "all-shows",
    title: "All Shows",
    movies: SHOW_MOVIES,
  },
];

export function getShowMovieById(id: string | null | undefined): Movie | undefined {
  if (!id) return undefined;
  return SHOW_MOVIES.find((m) => m.id === id);
}

export function getShowPlaylistByMovieId(movieId: string | null | undefined): Playlist | undefined {
  const movie = getShowMovieById(movieId);
  if (!movie) return undefined;
  return SHOW_PLAYLISTS.find((p) => p.id === movie.playlistId);
}

export function getShowEpisodeById(movieId: string | null | undefined, episodeId: string | null | undefined) {
  const playlist = getShowPlaylistByMovieId(movieId);
  if (!playlist) return undefined;
  return playlist.episodes.find((e) => e.id === episodeId);
}

export function getFeaturedShow(): Movie {
  return SHOW_MOVIES.find((m) => m.featured) ?? SHOW_MOVIES[0];
}