// AUTO-GENERATED from /upload/shows-update.txt + preserved yt-show entries
// Source: user-supplied show catalog (35 shows + 7 yt-show entries).
import { Movie, Playlist, MovieCategory } from "./types";

const SAMPLE_YT_IDS = [
  "aqz-KE-bpKQ",
  "eRsGyueVLvQ",
  "R6MlUcmOul8",
  "TLkA0RELQ1g",
  "WhWc3b3KhnY",
  "LXb3EKWsInQ",
  "fNqkXKKWBgs",
  "M7lc1UVf-VE",
  "MgIdv3iYYOw",
  "YbJOTdToBXs",
];

function makeEpisodes(prefix: string, showName: string, count: number, thumb: string) {
  const result: import("./types").Episode[] = [];
  for (let i = 0; i < count; i++) {
    const num = i + 1;
    result.push({
      id: `${prefix}-ep-${num}`,
      episodeNumber: num,
      seasonNumber: 1,
      title: `${showName} — Episode ${num}`,
      description: `Episode ${num} of ${showName}.`,
      duration: `${20 + (num % 15)}m`,
      thumbnail: thumb,
      youtubeId: SAMPLE_YT_IDS[i % SAMPLE_YT_IDS.length],
      airDate: `2024-${String((i % 12) + 1).padStart(2, "0")}-15`,
    });
  }
  return result;
}

export const SHOW_MOVIES: Movie[] = [
  {
    id: `gumball`,
    title: `The Amazing World of Gumball`,
    poster: `https://m.media-amazon.com/images/M/MV5BNmEwYzNhODgtZDc2Yi00MDAyLTliNWYtMDRkMThmMWE0NGNkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BNmEwYzNhODgtZDc2Yi00MDAyLTliNWYtMDRkMThmMWE0NGNkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`,
    year: 2011,
    rating: `TV-PG`,
    duration: `6 Seasons • 240 Eps`,
    genres: ["Komedi","Macera"],
    description: `Gumball Watterson ve ailesiyle Elmore şehrindeki çılgın gündelik maceralar.`,
    playlistId: `pl-gumball`,
    youtubePlaylistId: `PLC8MXDuDxrrsyqbTa9nK_gq8qmiMfR3sM`,
    featured: true,
  },
  {
    id: `fosters`,
    title: `Foster home for imaginary friends`,
    poster: `https://m.media-amazon.com/images/M/MV5BNTZjNzhkYjQtZDBhNS00NWM3LTk2NGUtZTkwODMyMTA4ZjdiXkEyXkFqcGc@._V1_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BNTZjNzhkYjQtZDBhNS00NWM3LTk2NGUtZTkwODMyMTA4ZjdiXkEyXkFqcGc@._V1_.jpg`,
    year: 2010,
    rating: `TV-PG`,
    duration: `1 Season • 49 Eps`,
    genres: ["Macera","Gizem"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-fosters`,
    youtubePlaylistId: `PL8ImJqzk7DAaA9mTiBYXh0Vs1oz9b3W2z`,
  },
  {
    id: `gumballtr`,
    title: `Gumball`,
    poster: `https://m.media-amazon.com/images/M/MV5BNmEwYzNhODgtZDc2Yi00MDAyLTliNWYtMDRkMThmMWE0NGNkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BNmEwYzNhODgtZDc2Yi00MDAyLTliNWYtMDRkMThmMWE0NGNkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`,
    year: 2008,
    rating: `TV-MA`,
    duration: `5 Seasons • 62 Eps`,
    genres: ["Drama","Suç"],
    description: `Kimya öğretmeni Walter White, kanser teşhisinin ardından uyuşturucu üretme dünyasına adım atar.`,
    playlistId: `pl-gumballtr`,
    youtubePlaylistId: `PLiR6LEIR8I0AeNLmoEbplwzELDMl6zaKu`,
  },
  {
    id: `theloudhouse`,
    title: `The Loud House`,
    poster: `https://m.media-amazon.com/images/M/MV5BZjlkMmQ5YzItZGRmMy00NjVjLWIwYmMtMzJjM2QxM2Q1OThkXkEyXkFqcGc@._V1_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BZjlkMmQ5YzItZGRmMy00NjVjLWIwYmMtMzJjM2QxM2Q1OThkXkEyXkFqcGc@._V1_.jpg`,
    year: 2016,
    rating: `TV-14`,
    duration: `4 Seasons • 34 Eps`,
    genres: ["Sci-Fi","Korku"],
    description: `Indiana'nın küçük kasabasında bir çocuğun kayboluşu, doğaüstü olayları gün yüzüne çıkarır.`,
    playlistId: `pl-theloudhouse`,
    youtubePlaylistId: `PLgrisE0MOLgRBNWk2cbO035kQ0hHA11HC`,
  },
  {
    id: `ben10ultimatealien`,
    title: `Ben 10 Alien Force`,
    poster: `https://mediaproxy.tvtropes.org/width/1200/https://static.tvtropes.org/pmwiki/pub/images/ben_10_ultimate_alien.png`,
    backdrop: `https://mediaproxy.tvtropes.org/width/1200/https://static.tvtropes.org/pmwiki/pub/images/ben_10_ultimate_alien.png`,
    year: 2011,
    rating: `TV-Y7-FV`,
    duration: `8 Seasons • 73 Eps`,
    genres: ["Fantezi","Aksiyon"],
    description: `Yedi krallığın Iron Throne'u için verilen güç mücadelesi epik bir destana dönüşür.`,
    playlistId: `pl-ben10ultimatealien`,
    youtubePlaylistId: `PLiR6LEIR8I0Cq9j-zCQL-X17Er-frDevZ`,
  },
  {
    id: `beybladex`,
    title: `Beyblade X`,
    poster: `https://m.media-amazon.com/images/M/MV5BMmM0OGU2NjgtYmE5ZS00MGU3LWFkYmQtODZkMThhMDA4ZTdmXkEyXkFqcGc@._V1_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BMmM0OGU2NjgtYmE5ZS00MGU3LWFkYmQtODZkMThhMDA4ZTdmXkEyXkFqcGc@._V1_.jpg`,
    year: 2019,
    rating: `TV-Y7-FV`,
    duration: `3 Seasons • 24 Eps`,
    genres: ["Fantezi","Aksiyon"],
    description: `Geralt of Rivia, canavarlarla dolu bir dünyada kendi kaderini arar.`,
    playlistId: `pl-beybladex`,
    youtubePlaylistId: `PLPVJvEAxGpArU5evWaOI33IVrjUEHMMba`,
  },
  {
    id: `SpongeBobSquarePants`,
    title: `SpongeBob SquarePants`,
    poster: `https://m.media-amazon.com/images/M/MV5BYjJmMjBkZjMtZThiZS00Nzk3LWJlN2UtYmE5ZjkyNjJiZjgxXkEyXkFqcGc@._V1_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BYjJmMjBkZjMtZThiZS00Nzk3LWJlN2UtYmE5ZjkyNjJiZjgxXkEyXkFqcGc@._V1_.jpg`,
    year: 2017,
    rating: `TV-PG`,
    duration: `3 Seasons • 26 Eps`,
    genres: ["Sci-Fi","Gizemli"],
    description: `Alman bir kasabada dört aile, zamanın dokusunu çözen bir gizemin içine sürüklenir.`,
    playlistId: `pl-SpongeBobSquarePants`,
    youtubePlaylistId: ``,
  },
  {
    id: `RegularShowLostTapestr`,
    title: `Regular Show Lost Tapes`,
    poster: `https://m.media-amazon.com/images/M/MV5BNDY5ZTA4ZGQtMzE2Ni00YjQ1LTk4ODktZGQwYTgwYWYxNjUwXkEyXkFqcGc@._V1_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BNDY5ZTA4ZGQtMzE2Ni00YjQ1LTk4ODktZGQwYTgwYWYxNjUwXkEyXkFqcGc@._V1_.jpg`,
    year: 2017,
    rating: `TV-MA`,
    duration: `4 Seasons • 44 Eps`,
    genres: ["Drama","Suç"],
    description: `Bir finansal danışman, ailesiyle birlikte Ozark'a taşınarak para aklamak zorunda kalır.`,
    playlistId: `pl-RegularShowLostTapestr`,
    youtubePlaylistId: `PLcwAUYauTRO-AhQH0olX4saDedFCbQgrk`,
  },
  {
    id: `AdventureTime`,
    title: `Adventure Time`,
    poster: `https://resizing.flixster.com/p4bNRltTA96oMxss5CJVBj0YvSU=/ems.cHJkLWVtcy1hc3NldHMvdHZzZXJpZXMvUlRUVjIwNDEwMy53ZWJw`,
    backdrop: `https://resizing.flixster.com/p4bNRltTA96oMxss5CJVBj0YvSU=/ems.cHJkLWVtcy1hc3NldHMvdHZzZXJpZXMvUlRUVjIwNDEwMy53ZWJw`,
    year: 2017,
    rating: `TV-MA`,
    duration: `5 Seasons • 41 Eps`,
    genres: ["Aksiyon","Suç"],
    description: `Bir dahi, müthiş bir soygun planı için beş suçluyu bir araya getirir.`,
    playlistId: `pl-AdventureTime`,
    youtubePlaylistId: `PLbAjUwk1iSda1NqtRb6emI0MQ_-UTIAKI`,
  },
  {
    id: `MutantNinjaTurtles`,
    title: `Teenage Mutant Ninja Turtles`,
    poster: `https://m.media-amazon.com/images/M/MV5BZTA0ZTlkMGItNTJmYy00YTVkLTgwMDktZTJiNTE5NmQ0ZWI4XkEyXkFqcGc@._V1_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BZTA0ZTlkMGItNTJmYy00YTVkLTgwMDktZTJiNTE5NmQ0ZWI4XkEyXkFqcGc@._V1_.jpg`,
    year: 2021,
    rating: `TV-MA`,
    duration: `2 Seasons • 9 Eps`,
    genres: ["Aksiyon","Drama"],
    description: `456 borçlu kişi, büyük ödül için ölüm kalım oyunlarında yarışır.`,
    playlistId: `pl-MutantNinjaTurtles`,
    youtubePlaylistId: `PL9FtL6eB-Npz_3om-MWlUXWQ87eWzaxl9`,
  },
  {
    id: `TransformersEarthSpark`,
    title: `Transformers EarthSpark`,
    poster: `https://m.media-amazon.com/images/M/MV5BNjAxNmRhZjctYTk1Ni00MGJjLThkY2YtNjdmODJjYTMwOGJlXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BNjAxNmRhZjctYTk1Ni00MGJjLThkY2YtNjdmODJjYTMwOGJlXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`,
    year: 2013,
    rating: `TV-MA`,
    duration: `6 Seasons • 36 Eps`,
    genres: ["Drama","Suç"],
    description: `1919 Birmingham'inde Shelby ailesi suç imparatorluğunu genişletmek için her yolu dener.`,
    playlistId: `pl-TransformersEarthSpark`,
    youtubePlaylistId: `PLYvpZVAr1p8pFCNEgzM4djvt9lbIKKzQ_`,
  },
  {
    id: `Ninjago`,
    title: `Ninjago`,
    poster: `https://m.media-amazon.com/images/M/MV5BNDY5ZTI1MzUtOWY4MC00NjFkLWEwNDctZWVlMTMzOWUwMDM1XkEyXkFqcGc@._V1_QL75_UY281_CR5,0,190,281_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BNDY5ZTI1MzUtOWY4MC00NjFkLWEwNDctZWVlMTMzOWUwMDM1XkEyXkFqcGc@._V1_QL75_UY281_CR5,0,190,281_.jpg`,
    year: 2019,
    rating: `TV-Y7-FV`,
    duration: `4 Seasons • 32 Eps`,
    genres: ["Aksiyon","Sci-Fi"],
    description: `Süper güçleri olan ama ahlaki değerleri olmayan kahramanları durdurmak için bir grup oluşturulur.`,
    playlistId: `pl-Ninjago`,
    youtubePlaylistId: `PLRNbTEZ7dhL04kIhO5L3_AX2gOmAfjX3T`,
  },
  {
    id: `gravityfallstr`,
    title: `Gravity Falls`,
    poster: `https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p9248224_b_v8_ax.jpg`,
    backdrop: `https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p9248224_b_v8_ax.jpg`,
    year: 2022,
    rating: `TV-MA`,
    duration: `2 Seasons • 18 Eps`,
    genres: ["Fantezi","Drama"],
    description: `Targaryen hanedanının iç savaşını konu alan Game of Thrones'un ön oyunu.`,
    playlistId: `pl-gravityfallstr`,
    youtubePlaylistId: `PLO7jGcCLf31VzYNKRuiGNjaIpS8Kb_fGB`,
  },
  {
    id: `stevenuniverse`,
    title: `Steven universe`,
    poster: `https://occ-0-55-56.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABZk8nf57NFcAOnS6m-G5YGDT2AtTL_BioQa4Vl-cEbmcNlHFMhphaUFWlqELLwAzffg2Ic5jPX5azzua87Usr9MlW1o2.jpg?r=c20`,
    backdrop: `https://occ-0-55-56.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABZk8nf57NFcAOnS6m-G5YGDT2AtTL_BioQa4Vl-cEbmcNlHFMhphaUFWlqELLwAzffg2Ic5jPX5azzua87Usr9MlW1o2.jpg?r=c20`,
    year: 2022,
    rating: `TV-PG`,
    duration: `2 Seasons • 16 Eps`,
    genres: ["Komedi","Gizem"],
    description: `Wednesday Addams'ın Nevermore Academy'deki maceralarını konu alan spin-off dizi.`,
    playlistId: `pl-stevenuniverse`,
    youtubePlaylistId: `PLIw4JuB69kRqSaga1p7kzPx99UOgrvRMA`,
  },
  {
    id: `FairlyOdd`,
    title: `The Fairly OddParents`,
    poster: `https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p186130_b_v8_az.jpg`,
    backdrop: `https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p186130_b_v8_az.jpg`,
    year: 2022,
    rating: `TV-PG`,
    duration: `2 Seasons • 16 Eps`,
    genres: ["Komedi","Gizem"],
    description: `Wednesday Addams'ın Nevermore Academy'deki maceralarını konu alan spin-off dizi.`,
    playlistId: `pl-FairlyOdd`,
    youtubePlaylistId: `PLZ0tJXxokwEHeQDwuaQffGxdOJBDed2dc`,
  },
  {
    id: `clarence`,
    title: `Clarence`,
    poster: `https://resizing.flixster.com/uye9Lk1HZO1BoVv8wul-eruCQ00=/fit-in/352x330/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p10517219_b_v12_ao.jpg`,
    backdrop: `https://resizing.flixster.com/uye9Lk1HZO1BoVv8wul-eruCQ00=/fit-in/352x330/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p10517219_b_v12_ao.jpg`,
    year: 2022,
    rating: `TV-PG`,
    duration: `2 Seasons • 16 Eps`,
    genres: ["Komedi","Gizem"],
    description: `Wednesday Addams'ın Nevermore Academy'deki maceralarını konu alan spin-off dizi.`,
    playlistId: `pl-clarence`,
    youtubePlaylistId: `PLiR6LEIR8I0Cx7JbsKYjV6r4K36yEZN0K`,
  },
  {
    id: `kamen`,
    title: `KAMEN RIDER ZEZTZ`,
    poster: `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTEX3L_FoDAPQnM55vlH57RPtcMIOKcsamZRQ&s`,
    backdrop: `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTEX3L_FoDAPQnM55vlH57RPtcMIOKcsamZRQ&s`,
    year: 2022,
    rating: `TV-PG`,
    duration: `2 Seasons • 16 Eps`,
    genres: ["Komedi","Gizem"],
    description: `Wednesday Addams'ın Nevermore Academy'deki maceralarını konu alan spin-off dizi.`,
    playlistId: `pl-kamen`,
    youtubePlaylistId: `PLPVJvEAxGpAoWTeKxp-uwehcgCM0Qb6k1`,
  },
  {
    id: `mira`,
    title: `MIRACULOUS`,
    poster: `https://m.media-amazon.com/images/M/MV5BODQ5NGFjZTQtNDkzNy00YWVjLWJiNGMtNTk1YzVmMmQ1YWQwXkEyXkFqcGc@._V1_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BODQ5NGFjZTQtNDkzNy00YWVjLWJiNGMtNTk1YzVmMmQ1YWQwXkEyXkFqcGc@._V1_.jpg`,
    year: 2022,
    rating: `TV-PG`,
    duration: `2 Seasons • 16 Eps`,
    genres: ["Komedi","Gizem"],
    description: `Wednesday Addams'ın Nevermore Academy'deki maceralarını konu alan spin-off dizi.`,
    playlistId: `pl-mira`,
    youtubePlaylistId: `PLKcPRfLkUNR527gRsdUn2zc7p30T-yC3Q`,
  },
  {
    id: `codename`,
    title: `Codename: Kids Next Door`,
    poster: `https://canvas-lb.tubitv.com/opts/QPgX3gZlSXk07Q==/ed7117d7-a2ec-4cb7-bfe9-baa7740474e8/CIACEPACOgUxLjEuOQ==`,
    backdrop: `https://canvas-lb.tubitv.com/opts/QPgX3gZlSXk07Q==/ed7117d7-a2ec-4cb7-bfe9-baa7740474e8/CIACEPACOgUxLjEuOQ==`,
    year: 2022,
    rating: `TV-PG`,
    duration: `2 Seasons • 16 Eps`,
    genres: ["Komedi","Gizem"],
    description: `Wednesday Addams'ın Nevermore Academy'deki maceralarını konu alan spin-off dizi.`,
    playlistId: `pl-codename`,
    youtubePlaylistId: `PLiR6LEIR8I0AwfEg8gT67vh1ysm8YT6Ba`,
  },
  {
    id: `circus`,
    title: `The Amazing Digital Circus`,
    poster: `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9Jma2VHSqeWhgFKxIzq_Q1J4uN_535pMhWw&s`,
    backdrop: `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9Jma2VHSqeWhgFKxIzq_Q1J4uN_535pMhWw&s`,
    year: 2022,
    rating: `TV-PG`,
    duration: `2 Seasons • 16 Eps`,
    genres: ["Komedi","Gizem"],
    description: `Wednesday Addams'ın Nevermore Academy'deki maceralarını konu alan spin-off dizi.`,
    playlistId: `pl-circus`,
    youtubePlaylistId: `PLHovnlOusNLgvAbnxluXCVB3KLj8e4QB-`,
  },
  {
    id: `nexoknights`,
    title: `nexo knights`,
    poster: `https://images.justwatch.com/poster/70363369/s718/lego-nexo-knights.jpg`,
    backdrop: `https://images.justwatch.com/poster/70363369/s718/lego-nexo-knights.jpg`,
    year: 2022,
    rating: `TV-PG`,
    duration: `2 Seasons • 16 Eps`,
    genres: ["Komedi","Macera"],
    description: `Wednesday Addams'ın Nevermore Academy'deki maceralarını konu alan spin-off dizi.`,
    playlistId: `pl-nexoknights`,
    youtubePlaylistId: `PLiR6LEIR8I0B35xfEeaHXgDKuqV1hD9Cc`,
  },
  {
    id: `ben10classic`,
    title: `Ben 10: Classic`,
    poster: `https://m.media-amazon.com/images/M/MV5BYWVjODZjNDgtYjk4ZS00OTg5LTg5NDQtZDMxZDQ4ZmM5MGJmXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BYWVjODZjNDgtYjk4ZS00OTg5LTg5NDQtZDMxZDQ4ZmM5MGJmXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`,
    year: 2022,
    rating: `TV-Y7-FV`,
    duration: `2 Seasons • 16 Eps`,
    genres: ["Komedi","Aksiyon"],
    description: `Wednesday Addams'ın Nevermore Academy'deki maceralarını konu alan spin-off dizi.`,
    playlistId: `pl-ben10classic`,
    youtubePlaylistId: `PLiR6LEIR8I0AU8atN4XfX1LewGAKz5KDO`,
  },
  {
    id: `ededdeddy`,
    title: `Ed, Edd n Eddy`,
    poster: `https://canvas-lb.tubitv.com/opts/45jLy-NKi6zMJQ==/075b8839-c779-4379-94f8-a6aadea9175c/CIACEPACOgUxLjEuOQ==`,
    backdrop: `https://canvas-lb.tubitv.com/opts/45jLy-NKi6zMJQ==/075b8839-c779-4379-94f8-a6aadea9175c/CIACEPACOgUxLjEuOQ==`,
    year: 2022,
    rating: `TV-PG`,
    duration: `2 Seasons • 16 Eps`,
    genres: ["Komedi","Gizem"],
    description: `Wednesday Addams'ın Nevermore Academy'deki maceralarını konu alan spin-off dizi.`,
    playlistId: `pl-ededdeddy`,
    youtubePlaylistId: `PLeTnF7L9vBEdFOhy4pn4pc7Gznn7BPHlw`,
  },
  {
    id: `kingshakir`,
    title: `King Shakir`,
    poster: `https://m.media-amazon.com/images/M/MV5BZTQyYmVhNTUtOTI2NS00MWI3LTk0NTgtZTk1MmU3YWY3NzkxXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BZTQyYmVhNTUtOTI2NS00MWI3LTk0NTgtZTk1MmU3YWY3NzkxXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`,
    year: 2022,
    rating: `TV-PG`,
    duration: `2 Seasons • 16 Eps`,
    genres: ["Komedi","Macera"],
    description: `Wednesday Addams'ın Nevermore Academy'deki maceralarını konu alan spin-off dizi.`,
    playlistId: `pl-kingshakir`,
    youtubePlaylistId: `PLgm-3QTfPk-j3dSjFU8FWgvIUmBcQkcEV`,
  },
  {
    id: `BigCityGreens`,
    title: `Big City Greens`,
    poster: `https://image.tmdb.org/t/p/original/mtUw50YnpZQcI6NJ4VsxSwTn6f1.jpg`,
    backdrop: `https://image.tmdb.org/t/p/original/mtUw50YnpZQcI6NJ4VsxSwTn6f1.jpg`,
    year: 2022,
    rating: `TV-PG`,
    duration: `2 Seasons • 16 Eps`,
    genres: ["Komedi","Macera"],
    description: `Wednesday Addams'ın Nevermore Academy'deki maceralarını konu alan spin-off dizi.`,
    playlistId: `pl-BigCityGreens`,
    youtubePlaylistId: `PLhSgw0LS-Vy_nhMiM4giG4DvLe8CsOx7z`,
  },
  {
    id: `evistar`,
    title: `Star vs. The Forces of Evil`,
    poster: `https://m.media-amazon.com/images/M/MV5BMTg1ZWIzNDAtNmFhOS00ZjhiLTg5ZWEtOWI4YzIzZTMxNGE2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BMTg1ZWIzNDAtNmFhOS00ZjhiLTg5ZWEtOWI4YzIzZTMxNGE2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`,
    year: 2022,
    rating: `TV-PG`,
    duration: `2 Seasons • 16 Eps`,
    genres: ["Komedi","Gizem"],
    description: `Wednesday Addams'ın Nevermore Academy'deki maceralarını konu alan spin-off dizi.`,
    playlistId: `pl-evistar`,
    youtubePlaylistId: `PLQkABKSgCWKmIXCP6Qxh8ADs8IUwCFtH4`,
  },
  {
    id: `Kimpossible`,
    title: `Kim Possible`,
    poster: `https://m.media-amazon.com/images/M/MV5BMmIwNjQ5MzEtNTg4Zi00NWMyLThkZDktZDg0MGU4MmYzMjlhXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BMmIwNjQ5MzEtNTg4Zi00NWMyLThkZDktZDg0MGU4MmYzMjlhXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`,
    year: 2010,
    rating: `TV-PG`,
    duration: `1 Season • 49 Eps`,
    genres: ["Macera","Gizem"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-Kimpossible`,
    youtubePlaylistId: `PLLhOnau-tupRiU2lBR78wDVYfi2mfC8DT`,
  },
  {
    id: `smash`,
    title: `Hulk Smash`,
    poster: `https://cdn.marvel.com/u/prod/marvel/i/mg/9/e0/691f3259cde3e/clean.jpg`,
    backdrop: `https://cdn.marvel.com/u/prod/marvel/i/mg/9/e0/691f3259cde3e/clean.jpg`,
    year: 2010,
    rating: `TV-PG`,
    duration: `1 Season • 49 Eps`,
    genres: ["Macera","Gizem"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-smash`,
    youtubePlaylistId: `PLSSaxseDVeB4NUyFG8QDF_xvRGH4_nbFE`,
  },
  {
    id: `spiderman`,
    title: `Spider-Man 2017`,
    poster: `https://cizgimax.online/img/locandine/marvels-spider-man-poster.webp`,
    backdrop: `https://cizgimax.online/img/locandine/marvels-spider-man-poster.webp`,
    year: 2010,
    rating: `TV-PG`,
    duration: `1 Season • 49 Eps`,
    genres: ["Macera","Gizem"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-spiderman`,
    youtubePlaylistId: `PLFg3ma1UtI3emejPwkVaPPvK_Pal8Bo6e`,
  },
  {
    id: `distandlands`,
    title: `Adventure Time: Distant Lands`,
    poster: `https://resizing.flixster.com/DyT34YI3TO_5fp_CPLof6WUor-c=/ems.cHJkLWVtcy1hc3NldHMvdHZzZXJpZXMvUlRUVjkyMjk2Mi53ZWJw`,
    backdrop: `https://resizing.flixster.com/DyT34YI3TO_5fp_CPLof6WUor-c=/ems.cHJkLWVtcy1hc3NldHMvdHZzZXJpZXMvUlRUVjkyMjk2Mi53ZWJw`,
    year: 2010,
    rating: `TV-PG`,
    duration: `1 Season • 49 Eps`,
    genres: ["Macera","Gizem"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-distandlands`,
    youtubePlaylistId: `PLmEWbcIX2pqr1ia5IvNpukZiVGKvDOG5M`,
  },
  {
    id: `samuraijack`,
    title: `Samurai Jack`,
    poster: `https://m.media-amazon.com/images/S/pv-target-images/fa8b7befffa2d22ece650c9e07c1b6c71b5308a70fd07b75cec0982c82c77791._UR2000,3000_.jpg`,
    backdrop: `https://m.media-amazon.com/images/S/pv-target-images/fa8b7befffa2d22ece650c9e07c1b6c71b5308a70fd07b75cec0982c82c77791._UR2000,3000_.jpg`,
    year: 2010,
    rating: `TV-PG`,
    duration: `1 Season • 49 Eps`,
    genres: ["Macera","Gizem"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-samuraijack`,
    youtubePlaylistId: `PLiR6LEIR8I0AiA4x5WXhX5OuO0Yc_7dnx`,
  },
  {
    id: `maxs`,
    title: `Max & The Midknights `,
    poster: `https://m.media-amazon.com/images/M/MV5BYjJiMTM4ZjUtMDMzNi00NTAxLThhOTktNTk3M2IwNTQxYzJkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BYjJiMTM4ZjUtMDMzNi00NTAxLThhOTktNTk3M2IwNTQxYzJkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`,
    year: 2010,
    rating: `TV-PG`,
    duration: `1 Season • 49 Eps`,
    genres: ["Macera","Gizem"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-maxs`,
    youtubePlaylistId: `PLUQR09yEYrP19UtlDyc4-mNC1eGyy-VtX`,
  },
  {
    id: `generator-rex`,
    title: `Generator Rex`,
    poster: `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAA801bMLg1gxTDY9vVIW3tEyl3dP58n-KOQ&s`,
    backdrop: `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAA801bMLg1gxTDY9vVIW3tEyl3dP58n-KOQ&s`,
    year: 2010,
    rating: `TV-PG`,
    duration: `1 Season • 49 Eps`,
    genres: ["Macera","Gizem"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-generator-rex`,
    youtubePlaylistId: `PLeWt4i89tklqXah-0HBdGhszq__G0Eozb`,
  },
  {
    id: `kafadaraycık`,
    title: `Kafadar ayıcıklar`,
    poster: `https://images.justwatch.com/poster/306826371/s718/kafadar-ayiciklar.jpg`,
    backdrop: `https://images.justwatch.com/poster/306826371/s718/kafadar-ayiciklar.jpg`,
    year: 2010,
    rating: `TV-PG`,
    duration: `1 Season • 49 Eps`,
    genres: ["Macera","Gizem"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-kafadaraycık`,
    youtubePlaylistId: `PLiR6LEIR8I0BFvw-COR1g0UM5WQYFskgf`,
  },
  {
    id: `fosters`,
    title: `Foster home for imaginary friends`,
    poster: `https://m.media-amazon.com/images/M/MV5BNTZjNzhkYjQtZDBhNS00NWM3LTk2NGUtZTkwODMyMTA4ZjdiXkEyXkFqcGc@._V1_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BNTZjNzhkYjQtZDBhNS00NWM3LTk2NGUtZTkwODMyMTA4ZjdiXkEyXkFqcGc@._V1_.jpg`,
    year: 2010,
    rating: `TV-PG`,
    duration: `1 Season • 49 Eps`,
    genres: ["Macera","Gizem"],
    description: `Desire Grand Prix'de yarışan kamen riderların kim olduğunu keşfetme yolculuğu.`,
    playlistId: `pl-fosters`,
    youtubePlaylistId: `PL8ImJqzk7DAaA9mTiBYXh0Vs1oz9b3W2z`,
  },
  {id: `yt-show-1`,
    title: `Geordie Shore`,
    poster: `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCWQ2oitZwkT6VpyrW5T-GiQJDPKbhlAhT7NAsp-wXVIqY8X7qzaj-eHmm&s=10`,
    backdrop: `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCWQ2oitZwkT6VpyrW5T-GiQJDPKbhlAhT7NAsp-wXVIqY8X7qzaj-eHmm&s=10`,
    year: 2024,
    rating: `TV-MA`,
    duration: `1 Season`,
    genres: ["Macera", "Reality"],
    description: `Geordie Shore — YouTube show. Bölüm listesi playlist'ten otomatik yüklenir.`,
    playlistId: `pl-yt-show-1`,
    youtubePlaylistId: `PLMmHigpjq0dw`,
  },
  {id: `yt-show-2`,
    title: `Just Tattoo of Us`,
    poster: `https://img.rgstatic.com/content/show/090164d3-ce59-41eb-bb88-b04fa1e1999f/poster-342.jpg`,
    backdrop: `https://img.rgstatic.com/content/show/090164d3-ce59-41eb-bb88-b04fa1e1999f/poster-342.jpg`,
    year: 2024,
    rating: `TV-14`,
    duration: `1 Season`,
    genres: ["Macera", "Reality"],
    description: `Just Tattoo of Us — YouTube show. Bölüm listesi playlist'ten otomatik yüklenir.`,
    playlistId: `pl-yt-show-2`,
    youtubePlaylistId: `PLWlbYPiFcSG8`,
  },
  {id: `yt-show-3`,
    title: `Roast Best Of Compilations`,
    poster: `https://m.media-amazon.com/images/S/pv-target-images/ca04e565c9a88486edc501ff81c7dc67b935cf2c5e5bf7493660a11bc2d73f1d._UR2000,3000_CLs%7C2000,3000%7C/G/bundle/BottomRightCardGradient2x3.png,/G/01/digital/video/merch/subs/benefit-id/a-f/cbsaacf/logos/channels-logo-white-stacked.png%7C0,0,2000,3000+0,0,2000,3000+1426,2798,487,115_kv4600e6e6b6650a7b1b1d469e8b864fb4_SX750_FMjpg_.jpg`,
    backdrop: `https://m.media-amazon.com/images/S/pv-target-images/ca04e565c9a88486edc501ff81c7dc67b935cf2c5e5bf7493660a11bc2d73f1d._UR2000,3000_CLs%7C2000,3000%7C/G/bundle/BottomRightCardGradient2x3.png,/G/01/digital/video/merch/subs/benefit-id/a-f/cbsaacf/logos/channels-logo-white-stacked.png%7C0,0,2000,3000+0,0,2000,3000+1426,2798,487,115_kv4600e6e6b6650a7b1b1d469e8b864fb4_SX750_FMjpg_.jpg`,
    year: 2024,
    rating: `TV-MA`,
    duration: `1 Season`,
    genres: ["Komedi", "Reality"],
    description: `Roast Best Of Compilations — YouTube playlist. En iyi roast anlarının derlemesi.`,
    playlistId: `pl-yt-show-3`,
    youtubePlaylistId: `PLD7nPL1U-R5qd19uN5dyGGOyE528rgB6y`,
  },
  {id: `yt-show-4`,
    title: `The Charlotte Show`,
    poster: `https://static.episodate.com/images/tv-show/full/62712.jpg`,
    backdrop: `https://static.episodate.com/images/tv-show/full/62712.jpg`,
    year: 2018,
    rating: `TV-14`,
    duration: `1 Season`,
    genres: ["Reality", "Drama"],
    description: `The Charlotte Show — YouTube playlist. Bölüm listesi playlist'ten otomatik yüklenir.`,
    playlistId: `pl-yt-show-4`,
    youtubePlaylistId: `PLcD7YRL9U84Q`,
  },
  {id: `yt-show-5`,
    title: `Teen Mom Australia`,
    poster: `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-wZ2ewY4Smtnxbu2FuSCtOJKUWreM9pTpxRBzW-fMJg&s=10`,
    backdrop: `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-wZ2ewY4Smtnxbu2FuSCtOJKUWreM9pTpxRBzW-fMJg&s=10`,
    year: 2019,
    rating: `TV-14`,
    duration: `1 Season`,
    genres: ["Reality", "Drama"],
    description: `Teen Mom Australia — YouTube show. Bölüm listesi playlist'ten otomatik yüklenir.`,
    playlistId: `pl-yt-show-5`,
    youtubePlaylistId: `PLI7JwFmvRkJQ`,
  },
  {id: `yt-show-6`,
    title: `The Blue Rose`,
    poster: `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4F6U6otaK8XGS0s5AMBP0jJZmmsnmlUaIqeV2fQRXwK0nqtXrl4GVdNdm&s=10`,
    backdrop: `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4F6U6otaK8XGS0s5AMBP0jJZmmsnmlUaIqeV2fQRXwK0nqtXrl4GVdNdm&s=10`,
    year: 2023,
    rating: `TV-14`,
    duration: `1 Season`,
    genres: ["Drama", "Gizem"],
    description: `The Blue Rose — YouTube playlist. Bölüm listesi playlist'ten otomatik yüklenir.`,
    playlistId: `pl-yt-show-6`,
    youtubePlaylistId: `PL_KQjFE9NyNsLiK_G8wnDIk0neoQktYOP`,
  },
  {id: `yt-show-7`,
    title: `Rules of Engagement`,
    poster: `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_jv5pCqLNwB8BIfKWCy95mdwgndJmYRN3KmqGBuOVl3LrMXs3fzS68rOG&s=10`,
    backdrop: `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_jv5pCqLNwB8BIfKWCy95mdwgndJmYRN3KmqGBuOVl3LrMXs3fzS68rOG&s=10`,
    year: 2007,
    rating: `TV-14`,
    duration: `1 Season`,
    genres: ["Komedi", "Romantik"],
    description: `Rules of Engagement — YouTube playlist. Bölüm listesi playlist'ten otomatik yüklenir.`,
    playlistId: `pl-yt-show-7`,
    youtubePlaylistId: `PLiZCl6XIGf-jJU3p4i5ZjneUiUPfl9nsL`,
  },
  {id: `yt-show-8`,
    title: `Jimmy Fallon BTS Series`,
    poster: `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdNTZUqN4PHHlgDmqE8L0IBVZ6e4d7L2g1_t2y039JsT2ALDlNFZnz7Jg-&s=10`,
    backdrop: `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdNTZUqN4PHHlgDmqE8L0IBVZ6e4d7L2g1_t2y039JsT2ALDlNFZnz7Jg-&s=10`,
    year: 2024,
    rating: `TV-14`,
    duration: `1 Season`,
    genres: ["Talk Show", "Komedi"],
    description: `Jimmy Fallon BTS Series — YouTube playlist. Bölüm listesi playlist'ten otomatik yüklenir.`,
    playlistId: `pl-yt-show-8`,
    youtubePlaylistId: `PLykzf464sU9_z3BXl7ne0r7ocHYTIozi5`,
  },
  {id: `yt-show-9`,
    title: `Tonight Show Games with Guests`,
    poster: `https://img.rgstatic.com/content/show/1e9df377-44e4-4e24-8e3b-290157030bc5/poster-342.jpg`,
    backdrop: `https://img.rgstatic.com/content/show/1e9df377-44e4-4e24-8e3b-290157030bc5/poster-342.jpg`,
    year: 2024,
    rating: `TV-14`,
    duration: `1 Season`,
    genres: ["Talk Show", "Komedi"],
    description: `Tonight Show Games with Guests — YouTube playlist. Bölüm listesi playlist'ten otomatik yüklenir.`,
    playlistId: `pl-yt-show-9`,
    youtubePlaylistId: `PLykzf464sU9-votkzDlaYlfBph5wLhxl8`,
  },
  {id: `yt-show-10`,
    title: `America's Got Talent`,
    poster: `https://image.tmdb.org/t/p/original/xyd4aV6LZ8dcj1etoMLroUxzFDf.jpg`,
    backdrop: `https://image.tmdb.org/t/p/original/xyd4aV6LZ8dcj1etoMLroUxzFDf.jpg`,
    year: 2006,
    rating: `TV-PG`,
    duration: `1 Season`,
    genres: ["Reality", "Yetenek"],
    description: `America's Got Talent — YouTube show. Bölüm listesi playlist'ten otomatik yüklenir.`,
    playlistId: `pl-yt-show-10`,
    youtubePlaylistId: `PLF-BDTAHX0p5fVi7dtN6PDI1su-ImJI54`,
  },
  {id: `yt-show-11`,
    title: `Bloomberg Radio`,
    poster: `https://imgsrv-sxm-prod-device.streaming.siriusxm.com/eyJrZXkiOiJhZW0vNTUvNTUxNGI3ZmEwZjNiNWJlZTEwZmVmMzRhMGVlMjUxMmRfMTcyNDg2NjEwNS5wbmciLCJlZGl0cyI6W3siZm9ybWF0Ijp7InR5cGUiOiJqcGVnIn19LHsicmVzaXplIjp7IndpZHRoIjozMTksImhlaWdodCI6MzE5fX1dfQ==`,
    backdrop: `https://imgsrv-sxm-prod-device.streaming.siriusxm.com/eyJrZXkiOiJhZW0vNTUvNTUxNGI3ZmEwZjNiNWJlZTEwZmVmMzRhMGVlMjUxMmRfMTcyNDg2NjEwNS5wbmciLCJlZGl0cyI6W3siZm9ybWF0Ijp7InR5cGUiOiJqcGVnIn19LHsicmVzaXplIjp7IndpZHRoIjozMTksImhlaWdodCI6MzE5fX1dfQ==`,
    year: 2024,
    rating: `TV-PG`,
    duration: `1 Season`,
    genres: ["News", "Finans"],
    description: `Bloomberg Radio — YouTube playlist. Canlı finans ve haber içerikleri.`,
    playlistId: `pl-yt-show-11`,
    youtubePlaylistId: `PLGaYlBJIOoa_UtErnnm27vEY_lk97A745`,
  },
  {id: `yt-show-12`,
    title: `Who Wants to Be a Millionaire?`,
    poster: `https://m.media-amazon.com/images/M/MV5BNzk5ZDhlMDMtYzM1ZS00NzBlLWJiZjMtZDYxNTc5NGQzMTI5XkEyXkFqcGc@._V1_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BNzk5ZDhlMDMtYzM1ZS00NzBlLWJiZjMtZDYxNTc5NGQzMTI5XkEyXkFqcGc@._V1_.jpg`,
    year: 1999,
    rating: `TV-PG`,
    duration: `1 Season`,
    genres: ["Yarışma", "Bilgi"],
    description: `Who Wants to Be a Millionaire? — YouTube playlist. Bölüm listesi playlist'ten otomatik yüklenir.`,
    playlistId: `pl-yt-show-12`,
    youtubePlaylistId: `PLOA8H8Jl1whxOIO3AAvWRXUbeA5Y0bNx5`,
  },
  {id: `yt-show-13`,
    title: `Just Keep Watching`,
    poster: `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTg9gfTUpg6uEaJ5f-dbI5JmWNps0wm3ijDhrxkTsjSyNG89Zh6hbQLaE0&s=10`,
    backdrop: `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTg9gfTUpg6uEaJ5f-dbI5JmWNps0wm3ijDhrxkTsjSyNG89Zh6hbQLaE0&s=10`,
    year: 2024,
    rating: `TV-14`,
    duration: `1 Season`,
    genres: ["Reality", "Macera"],
    description: `Just Keep Watching — YouTube show. Bölüm listesi playlist'ten otomatik yüklenir.`,
    playlistId: `pl-yt-show-13`,
    youtubePlaylistId: `PLdEipTmzqnN8`,
  },
  {id: `yt-show-14`,
    title: `Pirates Inc`,
    poster: `https://m.media-amazon.com/images/M/MV5BZjZmZWQxYTQtMGVmOC00NTZiLTk5NTctMDA3NTE2NmI1MDA4XkEyXkFqcGc@._V1_.jpg`,
    backdrop: `https://m.media-amazon.com/images/M/MV5BZjZmZWQxYTQtMGVmOC00NTZiLTk5NTctMDA3NTE2NmI1MDA4XkEyXkFqcGc@._V1_.jpg`,
    year: 2024,
    rating: `TV-14`,
    duration: `1 Season`,
    genres: ["Macera", "Komedi"],
    description: `Pirates Inc — YouTube show. Bölüm listesi playlist'ten otomatik yüklenir.`,
    playlistId: `pl-yt-show-14`,
    youtubePlaylistId: `PLXyOyZEVB9WE`,
  },
];

export const SHOW_PLAYLISTS: Playlist[] = [
  {
    id: `pl-gumball`,
    title: `The Amazing World of Gumball — Season 1`,
    description: `240 episodes across 6 seasons.`,
    episodes: makeEpisodes(`gumball`, `The Amazing World of Gumball`, 30, `https://m.media-amazon.com/images/M/MV5BNmEwYzNhODgtZDc2Yi00MDAyLTliNWYtMDRkMThmMWE0NGNkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`),
  },
  {
    id: `pl-fosters`,
    title: `Foster home for imaginary friends — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`fosters`, `Foster home for imaginary friends`, 30, `https://m.media-amazon.com/images/M/MV5BNTZjNzhkYjQtZDBhNS00NWM3LTk2NGUtZTkwODMyMTA4ZjdiXkEyXkFqcGc@._V1_.jpg`),
  },
  {
    id: `pl-gumballtr`,
    title: `Gumball — Season 1`,
    description: `62 episodes across 5 seasons.`,
    episodes: makeEpisodes(`gumballtr`, `Gumball`, 30, `https://m.media-amazon.com/images/M/MV5BNmEwYzNhODgtZDc2Yi00MDAyLTliNWYtMDRkMThmMWE0NGNkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`),
  },
  {
    id: `pl-theloudhouse`,
    title: `The Loud House — Season 1`,
    description: `34 episodes across 4 seasons.`,
    episodes: makeEpisodes(`theloudhouse`, `The Loud House`, 30, `https://m.media-amazon.com/images/M/MV5BZjlkMmQ5YzItZGRmMy00NjVjLWIwYmMtMzJjM2QxM2Q1OThkXkEyXkFqcGc@._V1_.jpg`),
  },
  {
    id: `pl-ben10ultimatealien`,
    title: `Ben 10 Alien Force — Season 1`,
    description: `73 episodes across 8 seasons.`,
    episodes: makeEpisodes(`ben10ultimatealien`, `Ben 10 Alien Force`, 30, `https://mediaproxy.tvtropes.org/width/1200/https://static.tvtropes.org/pmwiki/pub/images/ben_10_ultimate_alien.png`),
  },
  {
    id: `pl-beybladex`,
    title: `Beyblade X — Season 1`,
    description: `24 episodes across 3 seasons.`,
    episodes: makeEpisodes(`beybladex`, `Beyblade X`, 24, `https://m.media-amazon.com/images/M/MV5BMmM0OGU2NjgtYmE5ZS00MGU3LWFkYmQtODZkMThhMDA4ZTdmXkEyXkFqcGc@._V1_.jpg`),
  },
  {
    id: `pl-SpongeBobSquarePants`,
    title: `SpongeBob SquarePants — Season 1`,
    description: `26 episodes across 3 seasons.`,
    episodes: makeEpisodes(`SpongeBobSquarePants`, `SpongeBob SquarePants`, 26, `https://m.media-amazon.com/images/M/MV5BYjJmMjBkZjMtZThiZS00Nzk3LWJlN2UtYmE5ZjkyNjJiZjgxXkEyXkFqcGc@._V1_.jpg`),
  },
  {
    id: `pl-RegularShowLostTapestr`,
    title: `Regular Show Lost Tapes — Season 1`,
    description: `44 episodes across 4 seasons.`,
    episodes: makeEpisodes(`RegularShowLostTapestr`, `Regular Show Lost Tapes`, 30, `https://m.media-amazon.com/images/M/MV5BNDY5ZTA4ZGQtMzE2Ni00YjQ1LTk4ODktZGQwYTgwYWYxNjUwXkEyXkFqcGc@._V1_.jpg`),
  },
  {
    id: `pl-AdventureTime`,
    title: `Adventure Time — Season 1`,
    description: `41 episodes across 5 seasons.`,
    episodes: makeEpisodes(`AdventureTime`, `Adventure Time`, 30, `https://resizing.flixster.com/p4bNRltTA96oMxss5CJVBj0YvSU=/ems.cHJkLWVtcy1hc3NldHMvdHZzZXJpZXMvUlRUVjIwNDEwMy53ZWJw`),
  },
  {
    id: `pl-MutantNinjaTurtles`,
    title: `Teenage Mutant Ninja Turtles — Season 1`,
    description: `9 episodes across 2 seasons.`,
    episodes: makeEpisodes(`MutantNinjaTurtles`, `Teenage Mutant Ninja Turtles`, 9, `https://m.media-amazon.com/images/M/MV5BZTA0ZTlkMGItNTJmYy00YTVkLTgwMDktZTJiNTE5NmQ0ZWI4XkEyXkFqcGc@._V1_.jpg`),
  },
  {
    id: `pl-TransformersEarthSpark`,
    title: `Transformers EarthSpark — Season 1`,
    description: `36 episodes across 6 seasons.`,
    episodes: makeEpisodes(`TransformersEarthSpark`, `Transformers EarthSpark`, 30, `https://m.media-amazon.com/images/M/MV5BNjAxNmRhZjctYTk1Ni00MGJjLThkY2YtNjdmODJjYTMwOGJlXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`),
  },
  {
    id: `pl-Ninjago`,
    title: `Ninjago — Season 1`,
    description: `32 episodes across 4 seasons.`,
    episodes: makeEpisodes(`Ninjago`, `Ninjago`, 30, `https://m.media-amazon.com/images/M/MV5BNDY5ZTI1MzUtOWY4MC00NjFkLWEwNDctZWVlMTMzOWUwMDM1XkEyXkFqcGc@._V1_QL75_UY281_CR5,0,190,281_.jpg`),
  },
  {
    id: `pl-gravityfallstr`,
    title: `Gravity Falls — Season 1`,
    description: `18 episodes across 2 seasons.`,
    episodes: makeEpisodes(`gravityfallstr`, `Gravity Falls`, 18, `https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p9248224_b_v8_ax.jpg`),
  },
  {
    id: `pl-stevenuniverse`,
    title: `Steven universe — Season 1`,
    description: `16 episodes across 2 seasons.`,
    episodes: makeEpisodes(`stevenuniverse`, `Steven universe`, 16, `https://occ-0-55-56.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABZk8nf57NFcAOnS6m-G5YGDT2AtTL_BioQa4Vl-cEbmcNlHFMhphaUFWlqELLwAzffg2Ic5jPX5azzua87Usr9MlW1o2.jpg?r=c20`),
  },
  {
    id: `pl-FairlyOdd`,
    title: `The Fairly OddParents — Season 1`,
    description: `16 episodes across 2 seasons.`,
    episodes: makeEpisodes(`FairlyOdd`, `The Fairly OddParents`, 16, `https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p186130_b_v8_az.jpg`),
  },
  {
    id: `pl-clarence`,
    title: `Clarence — Season 1`,
    description: `16 episodes across 2 seasons.`,
    episodes: makeEpisodes(`clarence`, `Clarence`, 16, `https://resizing.flixster.com/uye9Lk1HZO1BoVv8wul-eruCQ00=/fit-in/352x330/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p10517219_b_v12_ao.jpg`),
  },
  {
    id: `pl-kamen`,
    title: `KAMEN RIDER ZEZTZ — Season 1`,
    description: `16 episodes across 2 seasons.`,
    episodes: makeEpisodes(`kamen`, `KAMEN RIDER ZEZTZ`, 16, `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTEX3L_FoDAPQnM55vlH57RPtcMIOKcsamZRQ&s`),
  },
  {
    id: `pl-mira`,
    title: `MIRACULOUS — Season 1`,
    description: `16 episodes across 2 seasons.`,
    episodes: makeEpisodes(`mira`, `MIRACULOUS`, 16, `https://m.media-amazon.com/images/M/MV5BODQ5NGFjZTQtNDkzNy00YWVjLWJiNGMtNTk1YzVmMmQ1YWQwXkEyXkFqcGc@._V1_.jpg`),
  },
  {
    id: `pl-codename`,
    title: `Codename: Kids Next Door — Season 1`,
    description: `16 episodes across 2 seasons.`,
    episodes: makeEpisodes(`codename`, `Codename: Kids Next Door`, 16, `https://canvas-lb.tubitv.com/opts/QPgX3gZlSXk07Q==/ed7117d7-a2ec-4cb7-bfe9-baa7740474e8/CIACEPACOgUxLjEuOQ==`),
  },
  {
    id: `pl-circus`,
    title: `The Amazing Digital Circus — Season 1`,
    description: `16 episodes across 2 seasons.`,
    episodes: makeEpisodes(`circus`, `The Amazing Digital Circus`, 16, `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9Jma2VHSqeWhgFKxIzq_Q1J4uN_535pMhWw&s`),
  },
  {
    id: `pl-nexoknights`,
    title: `nexo knights — Season 1`,
    description: `16 episodes across 2 seasons.`,
    episodes: makeEpisodes(`nexoknights`, `nexo knights`, 16, `https://images.justwatch.com/poster/70363369/s718/lego-nexo-knights.jpg`),
  },
  {
    id: `pl-ben10classic`,
    title: `Ben 10: Classic — Season 1`,
    description: `16 episodes across 2 seasons.`,
    episodes: makeEpisodes(`ben10classic`, `Ben 10: Classic`, 16, `https://m.media-amazon.com/images/M/MV5BYWVjODZjNDgtYjk4ZS00OTg5LTg5NDQtZDMxZDQ4ZmM5MGJmXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`),
  },
  {
    id: `pl-ededdeddy`,
    title: `Ed, Edd n Eddy — Season 1`,
    description: `16 episodes across 2 seasons.`,
    episodes: makeEpisodes(`ededdeddy`, `Ed, Edd n Eddy`, 16, `https://canvas-lb.tubitv.com/opts/45jLy-NKi6zMJQ==/075b8839-c779-4379-94f8-a6aadea9175c/CIACEPACOgUxLjEuOQ==`),
  },
  {
    id: `pl-kingshakir`,
    title: `King Shakir — Season 1`,
    description: `16 episodes across 2 seasons.`,
    episodes: makeEpisodes(`kingshakir`, `King Shakir`, 16, `https://m.media-amazon.com/images/M/MV5BZTQyYmVhNTUtOTI2NS00MWI3LTk0NTgtZTk1MmU3YWY3NzkxXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`),
  },
  {
    id: `pl-BigCityGreens`,
    title: `Big City Greens — Season 1`,
    description: `16 episodes across 2 seasons.`,
    episodes: makeEpisodes(`BigCityGreens`, `Big City Greens`, 16, `https://image.tmdb.org/t/p/original/mtUw50YnpZQcI6NJ4VsxSwTn6f1.jpg`),
  },
  {
    id: `pl-evistar`,
    title: `Star vs. The Forces of Evil — Season 1`,
    description: `16 episodes across 2 seasons.`,
    episodes: makeEpisodes(`evistar`, `Star vs. The Forces of Evil`, 16, `https://m.media-amazon.com/images/M/MV5BMTg1ZWIzNDAtNmFhOS00ZjhiLTg5ZWEtOWI4YzIzZTMxNGE2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`),
  },
  {
    id: `pl-Kimpossible`,
    title: `Kim Possible — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`Kimpossible`, `Kim Possible`, 30, `https://m.media-amazon.com/images/M/MV5BMmIwNjQ5MzEtNTg4Zi00NWMyLThkZDktZDg0MGU4MmYzMjlhXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`),
  },
  {
    id: `pl-smash`,
    title: `Hulk Smash — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`smash`, `Hulk Smash`, 30, `https://cdn.marvel.com/u/prod/marvel/i/mg/9/e0/691f3259cde3e/clean.jpg`),
  },
  {
    id: `pl-spiderman`,
    title: `Spider-Man 2017 — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`spiderman`, `Spider-Man 2017`, 30, `https://cizgimax.online/img/locandine/marvels-spider-man-poster.webp`),
  },
  {
    id: `pl-distandlands`,
    title: `Adventure Time: Distant Lands — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`distandlands`, `Adventure Time: Distant Lands`, 30, `https://resizing.flixster.com/DyT34YI3TO_5fp_CPLof6WUor-c=/ems.cHJkLWVtcy1hc3NldHMvdHZzZXJpZXMvUlRUVjkyMjk2Mi53ZWJw`),
  },
  {
    id: `pl-samuraijack`,
    title: `Samurai Jack — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`samuraijack`, `Samurai Jack`, 30, `https://m.media-amazon.com/images/S/pv-target-images/fa8b7befffa2d22ece650c9e07c1b6c71b5308a70fd07b75cec0982c82c77791._UR2000,3000_.jpg`),
  },
  {
    id: `pl-maxs`,
    title: `Max & The Midknights  — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`maxs`, `Max & The Midknights `, 30, `https://m.media-amazon.com/images/M/MV5BYjJiMTM4ZjUtMDMzNi00NTAxLThhOTktNTk3M2IwNTQxYzJkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg`),
  },
  {
    id: `pl-generator-rex`,
    title: `Generator Rex — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`generator-rex`, `Generator Rex`, 30, `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAA801bMLg1gxTDY9vVIW3tEyl3dP58n-KOQ&s`),
  },
  {
    id: `pl-kafadaraycık`,
    title: `Kafadar ayıcıklar — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`kafadaraycık`, `Kafadar ayıcıklar`, 30, `https://images.justwatch.com/poster/306826371/s718/kafadar-ayiciklar.jpg`),
  },
  {
    id: `pl-fosters`,
    title: `Foster home for imaginary friends — Season 1`,
    description: `49 episodes across 1 season.`,
    episodes: makeEpisodes(`fosters`, `Foster home for imaginary friends`, 30, `https://m.media-amazon.com/images/M/MV5BNTZjNzhkYjQtZDBhNS00NWM3LTk2NGUtZTkwODMyMTA4ZjdiXkEyXkFqcGc@._V1_.jpg`),
  },
  {id: `pl-yt-show-1`,
    title: `Geordie Shore — Season 1`,
    description: `YouTube show — episodes loaded from playlist.`,
    episodes: makeEpisodes(`yt-show-1`, `Geordie Shore`, 30, `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCWQ2oitZwkT6VpyrW5T-GiQJDPKbhlAhT7NAsp-wXVIqY8X7qzaj-eHmm&s=10`),
  },
  {id: `pl-yt-show-2`,
    title: `Just Tattoo of Us — Season 1`,
    description: `YouTube show — episodes loaded from playlist.`,
    episodes: makeEpisodes(`yt-show-2`, `Just Tattoo of Us`, 30, `https://img.rgstatic.com/content/show/090164d3-ce59-41eb-bb88-b04fa1e1999f/poster-342.jpg`),
  },
  {id: `pl-yt-show-3`,
    title: `Roast Best Of Compilations — Season 1`,
    description: `YouTube playlist — episodes loaded from playlist.`,
    episodes: makeEpisodes(`yt-show-3`, `Roast Best Of Compilations`, 30, `https://m.media-amazon.com/images/S/pv-target-images/ca04e565c9a88486edc501ff81c7dc67b935cf2c5e5bf7493660a11bc2d73f1d._UR2000,3000_CLs%7C2000,3000%7C/G/bundle/BottomRightCardGradient2x3.png,/G/01/digital/video/merch/subs/benefit-id/a-f/cbsaacf/logos/channels-logo-white-stacked.png%7C0,0,2000,3000+0,0,2000,3000+1426,2798,487,115_kv4600e6e6b6650a7b1b1d469e8b864fb4_SX750_FMjpg_.jpg`),
  },
  {id: `pl-yt-show-4`,
    title: `The Charlotte Show — Season 1`,
    description: `YouTube playlist — episodes loaded from playlist.`,
    episodes: makeEpisodes(`yt-show-4`, `The Charlotte Show`, 30, `https://static.episodate.com/images/tv-show/full/62712.jpg`),
  },
  {id: `pl-yt-show-5`,
    title: `Teen Mom Australia — Season 1`,
    description: `YouTube show — episodes loaded from playlist.`,
    episodes: makeEpisodes(`yt-show-5`, `Teen Mom Australia`, 30, `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-wZ2ewY4Smtnxbu2FuSCtOJKUWreM9pTpxRBzW-fMJg&s=10`),
  },
  {id: `pl-yt-show-6`,
    title: `The Blue Rose — Season 1`,
    description: `YouTube playlist — episodes loaded from playlist.`,
    episodes: makeEpisodes(`yt-show-6`, `The Blue Rose`, 30, `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4F6U6otaK8XGS0s5AMBP0jJZmmsnmlUaIqeV2fQRXwK0nqtXrl4GVdNdm&s=10`),
  },
  {id: `pl-yt-show-7`,
    title: `Rules of Engagement — Season 1`,
    description: `YouTube playlist — episodes loaded from playlist.`,
    episodes: makeEpisodes(`yt-show-7`, `Rules of Engagement`, 30, `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_jv5pCqLNwB8BIfKWCy95mdwgndJmYRN3KmqGBuOVl3LrMXs3fzS68rOG&s=10`),
  },
  {id: `pl-yt-show-8`,
    title: `Jimmy Fallon BTS Series — Season 1`,
    description: `YouTube playlist — episodes loaded from playlist.`,
    episodes: makeEpisodes(`yt-show-8`, `Jimmy Fallon BTS Series`, 30, `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdNTZUqN4PHHlgDmqE8L0IBVZ6e4d7L2g1_t2y039JsT2ALDlNFZnz7Jg-&s=10`),
  },
  {id: `pl-yt-show-9`,
    title: `Tonight Show Games with Guests — Season 1`,
    description: `YouTube playlist — episodes loaded from playlist.`,
    episodes: makeEpisodes(`yt-show-9`, `Tonight Show Games with Guests`, 30, `https://img.rgstatic.com/content/show/1e9df377-44e4-4e24-8e3b-290157030bc5/poster-342.jpg`),
  },
  {id: `pl-yt-show-10`,
    title: `America's Got Talent — Season 1`,
    description: `YouTube show — episodes loaded from playlist.`,
    episodes: makeEpisodes(`yt-show-10`, `America's Got Talent`, 30, `https://image.tmdb.org/t/p/original/xyd4aV6LZ8dcj1etoMLroUxzFDf.jpg`),
  },
  {id: `pl-yt-show-11`,
    title: `Bloomberg Radio — Season 1`,
    description: `YouTube playlist — episodes loaded from playlist.`,
    episodes: makeEpisodes(`yt-show-11`, `Bloomberg Radio`, 30, `https://imgsrv-sxm-prod-device.streaming.siriusxm.com/eyJrZXkiOiJhZW0vNTUvNTUxNGI3ZmEwZjNiNWJlZTEwZmVmMzRhMGVlMjUxMmRfMTcyNDg2NjEwNS5wbmciLCJlZGl0cyI6W3siZm9ybWF0Ijp7InR5cGUiOiJqcGVnIn19LHsicmVzaXplIjp7IndpZHRoIjozMTksImhlaWdodCI6MzE5fX1dfQ==`),
  },
  {id: `pl-yt-show-12`,
    title: `Who Wants to Be a Millionaire? — Season 1`,
    description: `YouTube playlist — episodes loaded from playlist.`,
    episodes: makeEpisodes(`yt-show-12`, `Who Wants to Be a Millionaire?`, 30, `https://m.media-amazon.com/images/M/MV5BNzk5ZDhlMDMtYzM1ZS00NzBlLWJiZjMtZDYxNTc5NGQzMTI5XkEyXkFqcGc@._V1_.jpg`),
  },
  {id: `pl-yt-show-13`,
    title: `Just Keep Watching — Season 1`,
    description: `YouTube show — episodes loaded from playlist.`,
    episodes: makeEpisodes(`yt-show-13`, `Just Keep Watching`, 30, `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTg9gfTUpg6uEaJ5f-dbI5JmWNps0wm3ijDhrxkTsjSyNG89Zh6hbQLaE0&s=10`),
  },
  {id: `pl-yt-show-14`,
    title: `Pirates Inc — Season 1`,
    description: `YouTube show — episodes loaded from playlist.`,
    episodes: makeEpisodes(`yt-show-14`, `Pirates Inc`, 30, `https://m.media-amazon.com/images/M/MV5BZjZmZWQxYTQtMGVmOC00NTZiLTk5NTctMDA3NTE2NmI1MDA4XkEyXkFqcGc@._V1_.jpg`),
  },
];

export const SHOW_CATEGORIES: MovieCategory[] = [
  {
    id: "trending",
    title: "Trending Now",
    movies: [SHOW_MOVIES[0], SHOW_MOVIES[1], SHOW_MOVIES[2], SHOW_MOVIES[3], SHOW_MOVIES[4], SHOW_MOVIES[5], SHOW_MOVIES[6], SHOW_MOVIES[7], SHOW_MOVIES[8], SHOW_MOVIES[9]],
  },
  {
    id: "popular-tv-series",
    title: "Popular TV Series",
    movies: [SHOW_MOVIES[35], SHOW_MOVIES[36], SHOW_MOVIES[37], SHOW_MOVIES[38], SHOW_MOVIES[39], SHOW_MOVIES[40], SHOW_MOVIES[41], SHOW_MOVIES[42], SHOW_MOVIES[43], SHOW_MOVIES[44], SHOW_MOVIES[45], SHOW_MOVIES[46], SHOW_MOVIES[47], SHOW_MOVIES[48]],
  },
  {
    id: "talk-show",
    title: "Talk Show",
    movies: [SHOW_MOVIES[42], SHOW_MOVIES[43]],
  },
  {
    id: "today-news",
    title: "Today, News",
    movies: [SHOW_MOVIES[45]],
  },
  {
    id: `komedi`,
    title: `Komedi`,
    movies: [SHOW_MOVIES[0], SHOW_MOVIES[13], SHOW_MOVIES[14], SHOW_MOVIES[15], SHOW_MOVIES[16], SHOW_MOVIES[17], SHOW_MOVIES[18], SHOW_MOVIES[19], SHOW_MOVIES[20], SHOW_MOVIES[21], SHOW_MOVIES[22], SHOW_MOVIES[23], SHOW_MOVIES[24], SHOW_MOVIES[25]],
  },
  {
    id: `macera`,
    title: `Macera`,
    movies: [SHOW_MOVIES[0], SHOW_MOVIES[1], SHOW_MOVIES[20], SHOW_MOVIES[23], SHOW_MOVIES[24], SHOW_MOVIES[26], SHOW_MOVIES[27], SHOW_MOVIES[28], SHOW_MOVIES[29], SHOW_MOVIES[30], SHOW_MOVIES[31], SHOW_MOVIES[32], SHOW_MOVIES[33], SHOW_MOVIES[34]],
  },
  {
    id: `gizem`,
    title: `Gizem`,
    movies: [SHOW_MOVIES[1], SHOW_MOVIES[13], SHOW_MOVIES[14], SHOW_MOVIES[15], SHOW_MOVIES[16], SHOW_MOVIES[17], SHOW_MOVIES[18], SHOW_MOVIES[19], SHOW_MOVIES[22], SHOW_MOVIES[25], SHOW_MOVIES[26], SHOW_MOVIES[27], SHOW_MOVIES[28], SHOW_MOVIES[29], SHOW_MOVIES[30], SHOW_MOVIES[31], SHOW_MOVIES[32], SHOW_MOVIES[33], SHOW_MOVIES[34]],
  },
  {
    id: `drama`,
    title: `Drama`,
    movies: [SHOW_MOVIES[2], SHOW_MOVIES[7], SHOW_MOVIES[9], SHOW_MOVIES[10], SHOW_MOVIES[12]],
  },
  {
    id: `suc`,
    title: `Suç`,
    movies: [SHOW_MOVIES[2], SHOW_MOVIES[7], SHOW_MOVIES[8], SHOW_MOVIES[10]],
  },
  {
    id: `sci-fi`,
    title: `Sci-Fi`,
    movies: [SHOW_MOVIES[3], SHOW_MOVIES[6], SHOW_MOVIES[11]],
  },
  {
    id: "all-shows",
    title: "All Shows",
    movies: SHOW_MOVIES,
  },
];

export function getShowMovieById(id: string | null | undefined): Movie | undefined {
  if (!id) return undefined;
  return SHOW_MOVIES.find((m) => m.id === id);
}

export function getShowPlaylistByMovieId(movieId: string | null | undefined): Playlist | undefined {
  const movie = getShowMovieById(movieId);
  if (!movie) return undefined;
  return SHOW_PLAYLISTS.find((p) => p.id === movie.playlistId);
}

export function getShowEpisodeById(movieId: string | null | undefined, episodeId: string | null | undefined) {
  const playlist = getShowPlaylistByMovieId(movieId);
  if (!playlist) return undefined;
  return playlist.episodes.find((e) => e.id === episodeId);
}

export function getFeaturedShow(): Movie {
  return SHOW_MOVIES.find((m) => m.featured) ?? SHOW_MOVIES[0];
}